export const unit = {
  n: 1,
  title: "The sentence",
  note: "What every English sentence needs, and the order it comes in",
  lessons: [
    {
      id: "sentence",
      title: "What makes a sentence",
      goal: "Say complete sentences with a subject and a verb",
      wm: "The Sentence",
      intro:
        "A sentence is a group of words that makes complete sense. In English almost every sentence needs two things: someone or something (the subject) and what they do or are (the verb). In Hindi and many Indian languages we often drop the subject, but English doesn’t let you.",
      rules: [
        ["Every sentence needs a verb.", "The office is near the station.", "She works from home."],
        ["Every sentence needs a subject, even when it is obvious. Use “it” for weather, time and distance.", "It is raining.", "It takes ten minutes to walk there."],
        ["Use “there is / there are” to say that something exists.", "There is a problem with my laptop.", "There are two meetings today."],
      ],
      mistakes: [
        ["Is raining.", "It is raining.", "English needs a subject, so we add “it”."],
        ["Very hot today.", "It is very hot today.", "Add a subject and a verb: it is."],
        ["In my office are many people.", "There are many people in my office.", "Use “there are” to say something exists."],
        ["My brother very tall.", "My brother is very tall.", "Don’t drop the verb “is”."],
      ],
      ex: [
        ["pick", "___ is very cold this morning.", ["It", "This", "There"], 0, "For weather we use “it” as the subject."],
        ["pick", "___ are three people waiting outside.", ["They", "There", "It"], 1, "“There are” says that something exists."],
        ["pick", "My manager ___ in Bangalore.", ["based", "is based", "being based"], 1, "The sentence needs a verb: is based."],
        ["pick", "___ takes two hours to reach Pune.", ["It", "There", "That"], 0, "For time and distance we use “it”."],
        ["spot", "Is very late, let's go home.", "Is", "It is", "The sentence has no subject. Add “it”."],
        ["spot", "My phone not working since morning.", "not working", "hasn't been working", "The sentence needs a verb: hasn’t been working."],
        ["spot", "In this city are many good schools.", "are", "there are", "Use “there are” for things that exist."],
        ["type", "___ is a meeting at four o’clock.", ["There"], "“There is” tells us something exists."],
        ["order", "It is too noisy in here.", "Subject (it) + verb (is) + the rest."],
        ["say", "Make it a full sentence: “Very crowded today.”", ["It is very crowded today", "It's very crowded today"], "Add the subject and the verb: It’s very crowded today."],
      ],
      talk: "Describe the weather and your street right now in three or four full sentences. Start each sentence with a subject, like “It is…” or “There are…”.",
    },
    {
      id: "kinds-of-sentences",
      title: "Statements, questions, requests",
      goal: "Change a statement into a question, a request or an exclamation",
      wm: "Kinds of Sentences",
      intro:
        "There are four kinds of sentences. A statement tells something. A question asks something. A request or order asks someone to do something. An exclamation shows a strong feeling. Each kind has its own word order and its own tone of voice.",
      rules: [
        ["A statement: subject first, then the verb.", "The train leaves at six.", "I don’t eat meat."],
        ["A question: the helping verb comes before the subject.", "Does the train leave at six?", "Are you coming?"],
        ["A request starts with the verb. Add “please” or “could you” to make it polite.", "Please close the door.", "Could you close the door?"],
        ["An exclamation often starts with “What a…” or “How…”.", "What a beautiful house!", "How kind of you!"],
      ],
      mistakes: [
        ["You are coming?", "Are you coming?", "In a question, put the helping verb before the subject."],
        ["What beautiful house!", "What a beautiful house!", "Use “What a” before a single thing."],
        ["How nice view!", "What a nice view!", "Use “What a” before a noun, and “How” before an adjective alone: How nice!"],
        ["Kindly do the needful.", "Could you please take care of this?", "“Do the needful” sounds old and unclear outside India. Say exactly what you need."],
      ],
      ex: [
        ["pick", "___ you free this evening?", ["Is", "Are", "Do"], 1, "With “you”, the question starts with “are”."],
        ["pick", "___ a lovely surprise!", ["What", "How", "What a"], 2, "Use “What a” before a single thing: What a lovely surprise!"],
        ["pick", "___ clever you are!", ["What", "How", "What a"], 1, "“How” goes before an adjective on its own."],
        ["pick", "___ you send me the file, please?", ["Could", "Are", "Did"], 0, "“Could you…?” makes a polite request."],
        ["spot", "You have finished the report?", "You have", "Have you", "Put the helping verb before the subject."],
        ["spot", "What an amazing idea it is?", "?", "!", "This is an exclamation, not a question."],
        ["spot", "How beautiful day it is!", "How", "What a", "Before a noun (day) use “What a”."],
        ["type", "___ a mess! Who did this?", ["What"], "What a mess!"],
        ["order", "Could you open the window, please?", "A polite request: Could you + verb."],
        ["say", "Make it a question: “She is your sister.”", ["Is she your sister"], "Swap the subject and “is”: Is she your sister?"],
      ],
      talk: "Imagine you are at a hotel reception. Ask three polite questions and make one request, like “Could you…?”.",
    },
    {
      id: "word-order",
      title: "Word order: who does what",
      goal: "Put the subject, verb and object in the English order",
      wm: "Subject and Predicate",
      intro:
        "English has a fixed order: Subject → Verb → Object → Place → Time. Hindi puts the verb at the end (“I tea drink”), but in English the verb comes right after the subject. Changing the order can change the meaning or just sound wrong.",
      rules: [
        ["Subject + verb + object.", "I drink tea.", "My sister teaches English."],
        ["Place comes before time.", "I go to the gym every morning.", "We met at the station yesterday."],
        ["Keep the verb and its object together. Don’t put a word between them.", "I like Indian food very much.", "She speaks English well."],
      ],
      mistakes: [
        ["I very much like Indian food.", "I like Indian food very much.", "“Very much” goes after the object."],
        ["She speaks well English.", "She speaks English well.", "Keep the verb and its object together."],
        ["Tomorrow I will go office.", "I will go to the office tomorrow.", "Place before time, and say “to the office”."],
        ["Tea I will have.", "I will have tea.", "In English the subject comes first, then the verb, then the object."],
      ],
      ex: [
        ["pick", "I ___ very much.", ["enjoy this song", "this song enjoy", "enjoy very this song"], 0, "Verb + object, then “very much”."],
        ["pick", "We met ___.", ["yesterday at the mall", "at the mall yesterday", "the mall yesterday at"], 1, "Place comes before time."],
        ["pick", "He plays ___.", ["well the guitar", "the guitar well", "good the guitar"], 1, "Keep the verb and object together: plays the guitar well."],
        ["pick", "My father reads ___.", ["every morning the newspaper", "the newspaper every morning", "the every morning newspaper"], 1, "Object first, then time."],
        ["spot", "I like very much your idea.", "very much your idea", "your idea very much", "“Very much” goes after the object."],
        ["spot", "She cooks very well Chinese food.", "very well Chinese food", "Chinese food very well", "Keep the verb and its object together."],
        ["spot", "I every day walk to work.", "every day walk to work", "walk to work every day", "Time words go at the end."],
        ["order", "She speaks three languages fluently.", "Subject + verb + object + how."],
        ["order", "We had lunch at a small cafe yesterday.", "Place before time."],
        ["say", "Put this in English order: “I coffee every morning drink.”", ["I drink coffee every morning"], "Subject + verb + object + time."],
      ],
      talk: "Tell the coach about your normal morning: what you do, where, and when. Use at least four sentences in the order subject, verb, object, place, time.",
    },
    {
      id: "phrases-clauses",
      title: "Phrases and clauses",
      goal: "Join two short ideas into one longer sentence",
      wm: "The Phrase and the Clause",
      intro:
        "A phrase is a group of words without its own subject and verb (“in the morning”). A clause has its own subject and verb (“when I woke up”). Good speakers join clauses with words like because, when, and, but, so that their ideas flow instead of coming out as many short pieces.",
      rules: [
        ["A phrase adds detail: where, when, how.", "I left in a hurry.", "She lives near the lake."],
        ["A clause has its own subject and verb.", "…because the bus was late.", "…when she called me."],
        ["Join two clauses with one joining word, not two.", "I was late because the bus didn’t come.", "Although it rained, we went out."],
      ],
      mistakes: [
        ["Because I was tired. So I slept early.", "I slept early because I was tired.", "“Because I was tired” is only half a sentence. Join it to the main clause."],
        ["Although it was late, but we continued.", "Although it was late, we continued.", "Use one joining word: although OR but, never both."],
        ["Since I was sick so I stayed home.", "Since I was sick, I stayed home.", "Don’t add “so” after “since” or “because”."],
        ["The man he called me yesterday.", "The man called me yesterday.", "Don’t repeat the subject with “he” or “she”."],
      ],
      ex: [
        ["pick", "___ it was raining, we played outside.", ["Although", "But", "So"], 0, "“Although” joins the two clauses."],
        ["pick", "I stayed home ___ I had a fever.", ["so", "because", "but"], 1, "The reason comes after “because”."],
        ["pick", "My friend ___ lives in Delhi.", ["he", "who", "—"], 2, "Don’t repeat the subject: My friend lives in Delhi."],
        ["pick", "She was tired, ___ she kept working.", ["because", "but", "although"], 1, "“But” shows a contrast between two full clauses."],
        ["spot", "Although he is rich, but he is not happy.", "but", "", "Use only one joining word: Although he is rich, he is not happy."],
        ["spot", "Because the traffic was bad so I came late.", "so", ",", "Don’t use “because” and “so” together."],
        ["spot", "My neighbour she is a doctor.", "she", "", "Don’t repeat the subject."],
        ["type", "I called you ___ I needed some help.", ["because", "as", "since"], "Give the reason with because."],
        ["order", "We went home early because it was raining.", "Main clause + because + reason."],
        ["say", "Join these with “because”: “I took a taxi. I was late.”", ["I took a taxi because I was late"], "Main idea first, then because + reason."],
      ],
      talk: "Talk about a day when something went wrong. Join your ideas with because, but, although, and when, instead of saying many short sentences.",
    },
  ],
};
