export const unit = {
  n: 6,
  title: "Perfect tenses and the future",
  note: "have done, have been doing, had done, will and going to",
  lessons: [
    {
      id: "present-perfect",
      title: "Present perfect: have done",
      goal: "Talk about experiences and recent news with have/has + past participle",
      wm: "Tenses: Present Perfect",
      intro:
        "The present perfect (have/has + past participle) connects the past to now. Use it for life experience (“I’ve been to Japan”), for news and recent results (“I’ve lost my keys”), and with ever, never, already, yet and just. The time is not stated, or it isn’t finished.",
      rules: [
        ["Experience, with no time given.", "I’ve visited Ladakh twice.", "Have you ever eaten sushi?"],
        ["A past action with a result now.", "She’s broken her phone. (It’s broken now.)", "I’ve finished the report."],
        ["with just, already, yet, ever, never.", "He’s just left.", "Have you finished yet? I haven’t started yet."],
      ],
      mistakes: [
        ["I have seen him yesterday.", "I saw him yesterday.", "A finished time (yesterday) needs the past simple."],
        ["Did you ever go to Kerala?", "Have you ever been to Kerala?", "For life experience, use the present perfect."],
        ["I have already did it.", "I have already done it.", "have + past participle (done)."],
        ["She has went home.", "She has gone home.", "go → went → gone"],
      ],
      ex: [
        ["pick", "I ___ that film three times.", ["saw", "have seen", "have saw"], 1, "Experience, no time given: have seen."],
        ["pick", "___ you ever ___ to Europe?", ["Did / go", "Have / been", "Have / went"], 1, "Experience: Have you ever been…?"],
        ["pick", "She ___ the company last year.", ["has joined", "joined", "has join"], 1, "A finished time: joined."],
        ["pick", "I’ve ___ finished. Give me one minute.", ["yet", "just", "ever"], 1, "just = a moment ago"],
        ["pick", "Have you replied to the email ___?", ["already", "yet", "just"], 1, "Questions end with yet."],
        ["spot", "I have met her last Monday.", "have met", "met", "“Last Monday” is finished: met."],
        ["spot", "He has wrote three books.", "wrote", "written", "has + past participle: written."],
        ["spot", "We have ate here before.", "ate", "eaten", "have + eaten"],
        ["type", "I have never ___ (drive) a truck.", ["driven"], "drive → drove → driven"],
        ["order", "Have you ever tried South Indian coffee?", "Have + you + ever + past participle"],
        ["say", "Correct this: “I have seen that movie yesterday.”", ["I saw that movie yesterday"], "Yesterday is finished, so use saw."],
      ],
      talk: "Tell the coach about places you’ve been, foods you’ve tried, and something you’ve never done but want to. Then say one thing you did last month, in the past simple.",
    },
    {
      id: "since-for",
      title: "Since and for: how long",
      goal: "Say how long with have been, since and for",
      wm: "Tenses: Present Perfect Continuous",
      intro:
        "To say how long something has continued up to now, English uses the present perfect (continuous), not the present tense: “I have lived here for five years”, “I have been working here since 2020”. “I am working here since 2020” is one of the most common Indian-English mistakes.",
      rules: [
        ["for + a length of time; since + a starting point.", "for two hours, for ten years", "since Monday, since 2019, since I was a child"],
        ["Action that continues to now: have/has been + -ing.", "I’ve been waiting for 20 minutes.", "She’s been learning guitar since March."],
        ["State verbs use have/has + past participle.", "I’ve known him for years.", "We’ve had this car since 2018."],
        ["Ask: How long have you…?", "How long have you been working here?", "How long have you known her?"],
      ],
      mistakes: [
        ["I am working here since 2020.", "I have been working here since 2020.", "Up to now: have been working."],
        ["I know him since childhood.", "I have known him since childhood.", "Up to now: have known."],
        ["I am waiting since two hours.", "I have been waiting for two hours.", "Length of time: for."],
        ["How long are you living here?", "How long have you been living here?", "Ask with have been."],
      ],
      ex: [
        ["pick", "I’ve lived in Mumbai ___ 2015.", ["for", "since", "from"], 1, "Starting point: since."],
        ["pick", "She’s been studying ___ three hours.", ["for", "since", "from"], 0, "Length of time: for."],
        ["pick", "We ___ each other since school.", ["know", "are knowing", "have known"], 2, "Up to now, state verb: have known."],
        ["pick", "How long ___ learning English?", ["are you", "have you been", "do you"], 1, "How long have you been…?"],
        ["pick", "He ___ for this company for ten years.", ["works", "is working", "has been working"], 2, "Up to now: has been working."],
        ["spot", "I am living in Chennai since 2018.", "am living", "have been living", "Up to now: have been living."],
        ["spot", "We have been waiting since forty minutes.", "since", "for", "Length of time: for."],
        ["spot", "How long do you know Rahul?", "do you know", "have you known", "Up to now: have you known."],
        ["type", "It’s been raining ___ this morning.", ["since"], "Starting point: since."],
        ["order", "I have been working here for six years.", "have been + -ing + for"],
        ["say", "Correct this: “I am working in this company since 2019.”", ["I have been working in this company since 2019", "I've been working in this company since 2019", "I have been working at this company since 2019"], "Up to now: I have been working…since."],
      ],
      talk: "Introduce your work or studies: how long you have been doing it, since when you have lived in your city, and how long you have known your best friend.",
    },
    {
      id: "past-perfect",
      title: "Past perfect: had done",
      goal: "Use “had done” only for the earlier of two past events",
      wm: "Tenses: Past Perfect",
      intro:
        "The past perfect (had + past participle) shows that one past action happened before another past action: “When I reached the station, the train had left.” Many Indian speakers use “had” for any past event (“I had gone to Delhi last week”), but in English that simply sounds wrong. For a single past event, use the past simple.",
      rules: [
        ["Earlier past: had + past participle. Later past: past simple.", "The film had started when we arrived.", "I had never seen snow before I went to Manali."],
        ["For one finished event, use the past simple.", "I went to Delhi last week.", "She called me yesterday."],
        ["With “after” and “before”, the past simple is often enough.", "After I finished work, I went home.", "I left before he arrived."],
      ],
      mistakes: [
        ["I had gone to Delhi last week.", "I went to Delhi last week.", "Only one past event: past simple."],
        ["Yesterday I had called you.", "I called you yesterday.", "Only one past event: past simple."],
        ["When I reached, the bus already left.", "When I reached the stop, the bus had already left.", "The earlier event takes “had left”."],
        ["She had came before me.", "She had come before me.", "had + past participle"],
      ],
      ex: [
        ["pick", "We ___ to the new office last month.", ["had moved", "moved", "have moved"], 1, "One past event: moved."],
        ["pick", "When I got home, everyone ___ dinner.", ["had eaten", "has eaten", "eats"], 0, "Earlier than getting home: had eaten."],
        ["pick", "I ___ never flown before that trip.", ["have", "had", "was"], 1, "Before a past trip: had never flown."],
        ["pick", "My uncle ___ us last Sunday.", ["had visited", "visited", "has visited"], 1, "One past event: visited."],
        ["spot", "Last year I had bought a new laptop.", "had bought", "bought", "One past event: bought."],
        ["spot", "By the time the police came, the thief escaped.", "escaped", "had escaped", "The escape happened earlier: had escaped."],
        ["spot", "I had spoke to him before the meeting.", "spoke", "spoken", "had + past participle: spoken."],
        ["type", "She was upset because she ___ (lose) her wallet.", ["had lost"], "Losing came first: had lost."],
        ["order", "The train had left when we reached the station.", "had + past participle for the earlier event"],
        ["say", "Correct this: “I had met him yesterday.”", ["I met him yesterday"], "One past event: met."],
      ],
      talk: "Tell a story about a time you were too late for something. Say what had already happened when you arrived.",
    },
    {
      id: "future",
      title: "Will, going to, and plans",
      goal: "Choose will, going to, or -ing for the future",
      wm: "Tenses: The Future",
      intro:
        "English has more than one future. “Will” is for decisions made now, promises and predictions. “Going to” is for plans you already decided and for things you can see coming. The present continuous is for arrangements with a time and a place. All three are correct; the difference is in how the speaker thinks.",
      rules: [
        ["will: a decision now, a promise, an offer, a prediction.", "I’ll call you tonight.", "Don’t worry, I’ll help you."],
        ["going to: a plan made before, or something you can see coming.", "I’m going to learn French this year.", "Look at those clouds. It’s going to rain."],
        ["present continuous: a fixed arrangement.", "I’m meeting the client at 3.", "We’re flying to Goa on Friday."],
      ],
      mistakes: [
        ["I will go to Shimla next week, we booked the tickets.", "I’m going to Shimla next week. We’ve booked the tickets.", "A fixed plan: going to / -ing."],
        ["Wait, I am helping you.", "Wait, I’ll help you.", "A decision at this moment: will."],
        ["I will be going to office tomorrow.", "I’m going to the office tomorrow.", "Simple, natural plan: I’m going to the office."],
        ["He will reaches soon.", "He will reach soon.", "will + base form"],
      ],
      ex: [
        ["pick", "The phone is ringing. — I ___ get it.", ["will", "am going to", "am"], 0, "A decision now: I’ll get it."],
        ["pick", "We ___ buy a new car next year. We’ve been saving for it.", ["will", "are going to", "go to"], 1, "A plan made before: going to."],
        ["pick", "I ___ my dentist at 4 tomorrow.", ["see", "am seeing", "saw"], 1, "Fixed arrangement: am seeing."],
        ["pick", "Look out! You ___ fall!", ["will", "are going to", "fall"], 1, "You can see it coming: going to."],
        ["pick", "I promise I ___ tell anyone.", ["won’t", "am not going", "don’t"], 0, "A promise: won’t."],
        ["spot", "Don't worry, I am sending the file in five minutes.", "am sending", "will send", "A promise / offer: will send."],
        ["spot", "She will reaches home by eight.", "reaches", "reach", "will + base form"],
        ["spot", "Tomorrow I go to the doctor at ten.", "go", "am going", "A fixed arrangement: am going."],
        ["type", "It’s so hot. I think I ___ (have) a cold drink.", ["will have", "'ll have", "’ll have"], "A decision now: I’ll have."],
        ["order", "I'm going to start running next month.", "A plan: going to + base form."],
        ["say", "Offer help with “will”: your friend’s bag is heavy.", ["I will carry it*", "I will help*", "I will take it*", "Let me*"], "A quick offer: I’ll carry it / I’ll help you."],
      ],
      talk: "Talk about your plans for next weekend and next year, and make two predictions about your city in ten years.",
    },
    {
      id: "time-clauses",
      title: "When I reach, not when I will reach",
      goal: "Use the present after when, as soon as, after, before and until",
      wm: "The Sequence of Tenses",
      intro:
        "After time words like when, as soon as, before, after and until, English uses the present tense to talk about the future: “I’ll call you when I reach.” Saying “when I will reach” is one of the most common Indian-English errors. The “will” goes only in the other half of the sentence.",
      rules: [
        ["Future sentence: will + … + when/after/before/until + present.", "I’ll call you when I get home.", "We’ll start as soon as he arrives."],
        ["Same with “if”: if + present, will + verb.", "If it rains, we’ll stay in.", "If you need anything, I’ll be here."],
        ["For a finished future action, use present perfect after when.", "I’ll send it when I’ve finished.", "You can go after you’ve eaten."],
      ],
      mistakes: [
        ["I will call you when I will reach.", "I’ll call you when I reach.", "After “when”, use the present."],
        ["Wait until he will come.", "Wait until he comes.", "After “until”, use the present."],
        ["If you will come, we will go.", "If you come, we’ll go.", "After “if”, use the present."],
        ["As soon as I will get the results, I will tell you.", "As soon as I get the results, I’ll tell you.", "After “as soon as”, use the present."],
      ],
      ex: [
        ["pick", "Text me when you ___ home.", ["will reach", "reach", "reached"], 1, "After when: present."],
        ["pick", "I’ll wait here until you ___.", ["come back", "will come back", "came back"], 0, "After until: present."],
        ["pick", "If she ___ late, we’ll start without her.", ["will be", "is", "was"], 1, "After if: present."],
        ["pick", "We ___ dinner after the guests arrive.", ["serve", "will serve", "served"], 1, "Main clause: will serve."],
        ["spot", "I will tell him when he will come.", "will come", "comes", "After when: comes."],
        ["spot", "Don't leave until the meeting will finish.", "will finish", "finishes", "After until: finishes."],
        ["spot", "As soon as I will get the money, I will pay you.", "will get", "get", "After as soon as: get."],
        ["type", "Call me as soon as you ___ (land).", ["land"], "After as soon as: present."],
        ["order", "I will send you the photos when I get home.", "will … when + present"],
        ["say", "Correct this: “I will message you when I will reach.”", ["I will message you when I reach", "I'll message you when I reach", "I will text you when I reach", "I'll text you when I reach"], "After when: present."],
      ],
      talk: "Tell the coach your plan for tomorrow using when, after, before and as soon as: “When I wake up, I’ll…”. Keep “will” out of the time half.",
    },
  ],
};
