export const unit = {
  n: 4,
  title: "Describing things",
  note: "Adjectives, comparing, too and enough",
  lessons: [
    {
      id: "adjectives",
      title: "Bored or boring? Adjectives",
      goal: "Choose -ed or -ing adjectives, and put adjectives in the right place",
      wm: "The Adjective",
      intro:
        "Adjectives describe nouns. In English they come before the noun (“a quiet street”) or after verbs like be, look, feel, seem (“the street is quiet”). They never take a plural -s. Two adjective families confuse many learners: -ed words describe how you feel, and -ing words describe what causes the feeling.",
      rules: [
        ["-ed = how a person feels. -ing = the thing that causes it.", "I was bored. The lecture was boring.", "She is interested in art. Art is interesting."],
        ["Adjectives never take -s.", "two old houses (not “olds”)", "They are happy."],
        ["After look, feel, seem, sound, taste, smell: use an adjective, not -ly.", "You look tired.", "This soup tastes good."],
      ],
      mistakes: [
        ["I am very boring today.", "I am very bored today.", "“Boring” means you make others bored!"],
        ["The movie was very excited.", "The movie was very exciting.", "The movie causes the feeling: exciting."],
        ["She looks beautifully.", "She looks beautiful.", "After “look”, use an adjective."],
        ["I feel very badly.", "I feel very bad.", "After “feel”, use an adjective."],
      ],
      ex: [
        ["pick", "I was really ___ by the news.", ["surprising", "surprised"], 1, "How I felt: surprised."],
        ["pick", "The trip was long and ___.", ["tiring", "tired"], 0, "The trip caused the feeling: tiring."],
        ["pick", "Are you ___ in cricket?", ["interesting", "interested"], 1, "How you feel: interested."],
        ["pick", "The food smells ___.", ["wonderfully", "wonderful"], 1, "After “smell”, use an adjective."],
        ["pick", "They are very ___ people.", ["kinds", "kind", "kindly"], 1, "Adjectives never take -s."],
        ["spot", "I'm so exciting about the trip!", "exciting", "excited", "How you feel: excited."],
        ["spot", "The meeting was very confused.", "confused", "confusing", "The meeting caused the feeling: confusing."],
        ["spot", "Your plan sounds perfectly.", "perfectly", "perfect", "After “sound”, use an adjective."],
        ["type", "I get ___ when people are late. (annoyed / annoying)", ["annoyed"], "How you feel: annoyed."],
        ["order", "The last episode was really disappointing.", "The episode caused the feeling: disappointing."],
        ["say", "Correct this: “I was very boring in the class.”", ["I was very bored in the class", "I was very bored in class"], "How you felt: bored."],
      ],
      talk: "Talk about a film or series you watched recently. Was it boring or interesting? How did you feel? Use at least three -ed and -ing adjectives.",
    },
    {
      id: "comparing",
      title: "Bigger, more careful, the best",
      goal: "Compare two or more things without “more better”",
      wm: "Comparison of Adjectives",
      intro:
        "To compare two things, add -er to short adjectives (cheap → cheaper) or put “more” before long ones (more expensive), then use “than”. For three or more, use “the” + -est or “the most”. Never use both: “more better” is wrong.",
      rules: [
        ["Short: -er than / the -est.", "Delhi is bigger than Jaipur.", "This is the cheapest option."],
        ["Long: more … than / the most.", "This phone is more expensive than mine.", "She is the most talented singer here."],
        ["Irregular: good → better → the best; bad → worse → the worst; far → further.", "Your English is better than mine.", "That was the worst day of my life."],
        ["Use “than”, not “then”, and never “more” with -er.", "He is taller than me.", "It’s easier now."],
      ],
      mistakes: [
        ["This is more better.", "This is better.", "Don’t use “more” with “better”."],
        ["She is more elder than me.", "She is older than me.", "“Elder” isn’t used with “than”; say “older than”."],
        ["He is senior than me.", "He is senior to me.", "Senior, junior, superior and prior take “to”."],
        ["Mumbai is most crowded city.", "Mumbai is the most crowded city.", "Superlatives need “the”."],
        ["She is more smarter than him.", "She is smarter than him.", "Just “smarter”."],
      ],
      ex: [
        ["pick", "Today is ___ than yesterday.", ["hotter", "more hot", "more hotter"], 0, "Short word: hotter."],
        ["pick", "This is ___ film I have ever seen.", ["the worse", "the worst", "the most bad"], 1, "bad → worse → the worst"],
        ["pick", "Train travel is ___ than flying.", ["more relaxing", "relaxinger", "most relaxing"], 0, "Long word: more relaxing."],
        ["pick", "My brother is two years ___ me.", ["elder than", "older than", "elder to"], 1, "Use “older than”."],
        ["pick", "She is junior ___ me in the office.", ["than", "to", "from"], 1, "junior to"],
        ["spot", "Your idea is more better than mine.", "more better", "better", "Don’t use “more” with “better”."],
        ["spot", "He is the most tallest boy in the class.", "most tallest", "tallest", "Use one form: the tallest."],
        ["spot", "Bangalore is cooler then Chennai.", "then", "than", "Comparisons use “than”."],
        ["type", "This is the ___ day of the year. (hot)", ["hottest"], "hot → hotter → the hottest"],
        ["order", "Walking is healthier than driving.", "-er + than"],
        ["say", "Correct this: “My new job is more better than my old job.”", ["My new job is better than my old job", "My new job is better than my old one"], "better, not more better"],
      ],
      talk: "Compare two cities you know: which is bigger, cleaner, more expensive, and which is the best place to live? Use at least five comparisons.",
    },
    {
      id: "too-enough-so-such",
      title: "Too, enough, very, so, such",
      goal: "Say how much with too, enough, very, so and such",
      wm: "Adjectives and Adverbs of Degree",
      intro:
        "“Very” makes a word stronger. “Too” means more than you want: it’s a problem. “Enough” means as much as needed, and comes after an adjective. “So” goes before an adjective alone; “such” goes before a noun: so kind, such a kind man.",
      rules: [
        ["too = more than is good.", "It’s too hot to go out.", "The shirt is too big for me."],
        ["adjective + enough; enough + noun.", "He isn’t old enough to drive.", "We don’t have enough chairs."],
        ["so + adjective; such (a) + adjective + noun.", "She is so kind.", "She is such a kind person."],
      ],
      mistakes: [
        ["The food is too tasty!", "The food is very tasty! / so tasty!", "“Too” is for problems. For praise, use very or so."],
        ["He is enough tall to play.", "He is tall enough to play.", "“Enough” comes after the adjective."],
        ["It was so a good day.", "It was such a good day.", "Before “a + noun”, use “such”."],
        ["I am too much happy.", "I am very happy.", "Don’t say “too much” before adjectives."],
      ],
      ex: [
        ["pick", "Your house is ___ beautiful!", ["too", "very", "enough"], 1, "Praise: very."],
        ["pick", "I can’t drink this tea. It’s ___ hot.", ["too", "very", "such"], 0, "A problem: too hot."],
        ["pick", "Is the room big ___ for ten people?", ["too", "enough", "so"], 1, "big enough"],
        ["pick", "It was ___ a long day.", ["so", "such", "too"], 1, "such + a + noun"],
        ["pick", "We don’t have ___ to finish today.", ["time enough", "enough time", "too time"], 1, "enough + noun"],
        ["spot", "You look too nice in that dress!", "too", "very", "Praise: very, not too."],
        ["spot", "She isn't enough experienced for this role.", "enough experienced", "experienced enough", "Adjective + enough."],
        ["spot", "He is so a funny guy.", "so a", "such a", "such + a + noun"],
        ["type", "The bag is ___ heavy for me to lift.", ["too"], "A problem: too heavy."],
        ["order", "It was such a relaxing holiday.", "such + a + adjective + noun"],
        ["say", "Correct this: “Your cooking is too good!”", ["Your cooking is very good", "Your cooking is so good", "Your cooking is really good"], "Praise uses very, so, or really."],
      ],
      talk: "Describe your room or office. What is too small or too noisy, what isn’t big enough, and what is so nice about it?",
    },
  ],
};
