export const unit = {
  n: 7,
  title: "Questions and answers",
  note: "Asking, saying no, question tags, and short replies",
  lessons: [
    {
      id: "questions",
      title: "Asking questions",
      goal: "Put the helping verb before the subject in every question",
      wm: "Interrogative Sentences",
      intro:
        "In spoken Indian English, questions often keep statement order: “Why you are late?”, “Where you went?”. In standard English, a question needs a helping verb (do, does, did, is, are, have, can…) before the subject. The order is: question word + helping verb + subject + main verb.",
      rules: [
        ["Question word + helping verb + subject + verb.", "Where do you live?", "Why are you late?"],
        ["No helping verb in the statement? Add do / does / did.", "She works here. → Does she work here?", "They left. → When did they leave?"],
        ["When the question word IS the subject, keep normal order.", "Who called you? (not “Who did call you?”)", "What happened?"],
      ],
      mistakes: [
        ["Why you are late?", "Why are you late?", "Helping verb before the subject."],
        ["Where you went yesterday?", "Where did you go yesterday?", "Add “did” and use the base form."],
        ["What he is saying?", "What is he saying?", "Helping verb before the subject."],
        ["Who did tell you this?", "Who told you this?", "“Who” is the subject, so no “did”."],
      ],
      ex: [
        ["pick", "What time ___ the shop open?", ["do", "does", "is"], 1, "the shop → does"],
        ["pick", "Where ___ you last night?", ["you were", "were you", "did you"], 1, "Helping verb first: were you."],
        ["pick", "___ told you about the party?", ["Who", "Who did", "Whom did"], 0, "Who is the subject: Who told you?"],
        ["pick", "How long ___ you been here?", ["are", "have", "did"], 1, "Present perfect: have you been."],
        ["pick", "Why ___ she leave early?", ["did", "was", "is"], 0, "Past simple question: did she leave."],
        ["spot", "Why you didn't call me?", "you didn't", "didn't you", "Helping verb before the subject."],
        ["spot", "Where you are going?", "you are", "are you", "Helping verb before the subject."],
        ["spot", "What did happen at the meeting?", "did happen", "happened", "What is the subject: What happened?"],
        ["type", "How much ___ this phone cost?", ["does"], "this phone → does"],
        ["order", "Where did you buy that shirt?", "Question word + did + subject + base form"],
        ["say", "Make a question with “where”: “She works in Gurgaon.”", ["Where does she work"], "Where + does + she + work?"],
      ],
      talk: "Imagine you are meeting a new colleague. Ask them six questions about their life and work, using where, what, how long, why, and do/does.",
    },
    {
      id: "indirect-questions",
      title: "Can you tell me where it is?",
      goal: "Ask polite indirect questions with normal word order",
      wm: "Noun Clauses; Reported Questions",
      intro:
        "Polite questions often start with “Can you tell me…”, “Do you know…”, or “I wonder…”. After these openings, the second part goes back to normal statement order and loses do/does/did: “Can you tell me where the station is?” (not “where is the station”).",
      rules: [
        ["Opening + question word + subject + verb.", "Do you know what time it is?", "Can you tell me where he lives?"],
        ["Yes/no questions: use if or whether.", "Do you know if the shop is open?", "I wonder whether she’ll come."],
        ["Drop do/does/did in the second part.", "Could you tell me when the train leaves?", "Do you know why he left?"],
      ],
      mistakes: [
        ["Can you tell me where is the bank?", "Can you tell me where the bank is?", "After “Can you tell me”, use statement order."],
        ["Do you know what time does the film start?", "Do you know what time the film starts?", "Drop “does”, add -s."],
        ["I don’t know where did he go.", "I don’t know where he went.", "Statement order, past form."],
        ["Can you tell me is he coming?", "Can you tell me if he is coming?", "Use “if” for yes/no."],
      ],
      ex: [
        ["pick", "Do you know where ___?", ["is the post office", "the post office is", "does the post office"], 1, "Statement order."],
        ["pick", "Could you tell me what time ___?", ["the bus leaves", "does the bus leave", "leaves the bus"], 0, "Statement order, no “does”."],
        ["pick", "I wonder ___ she got the job.", ["that", "if", "did"], 1, "Yes/no: if or whether."],
        ["pick", "Can you tell me how much ___?", ["does it cost", "it costs", "costs it"], 1, "Statement order."],
        ["spot", "Do you know where does Priya live?", "does Priya live", "Priya lives", "Statement order: Priya lives."],
        ["spot", "Can you tell me what is your name?", "is your name", "your name is", "Statement order."],
        ["spot", "I don't know why did they cancel it.", "did they cancel", "they cancelled", "Statement order, past form."],
        ["type", "Do you know ___ the meeting is still on? (yes/no)", ["if", "whether"], "Yes/no: if or whether."],
        ["order", "Could you tell me where the lift is?", "Opening + where + subject + verb"],
        ["say", "Make it polite. Start with “Could you tell me”: “Where is the ATM?”", ["Could you tell me where the ATM is"], "Statement order at the end: where the ATM is."],
      ],
      talk: "You are in a new city. Ask the coach five polite questions starting with “Could you tell me…” or “Do you know…”.",
    },
    {
      id: "negatives",
      title: "Saying no",
      goal: "Make negatives without doubling or mixing forms",
      wm: "Negative Sentences",
      intro:
        "To make a sentence negative, add “not” after the helping verb: isn’t, don’t, didn’t, haven’t, can’t, won’t. If there’s no helping verb, add do/does/did. Use only one negative word in a sentence: “I don’t know anything”, not “I don’t know nothing”.",
      rules: [
        ["helping verb + not.", "She isn’t here.", "We haven’t decided."],
        ["don’t / doesn’t / didn’t + base form.", "He doesn’t smoke.", "I didn’t see it."],
        ["One negative per sentence. Use any / anything / anyone after a negative.", "I didn’t tell anyone.", "There isn’t anything to eat."],
      ],
      mistakes: [
        ["I don’t know nothing.", "I don’t know anything.", "Only one negative."],
        ["He not coming today.", "He isn’t coming today.", "Add the helping verb: isn’t."],
        ["She didn’t called me.", "She didn’t call me.", "didn’t + base form"],
        ["No, I didn’t went.", "No, I didn’t go.", "didn’t + base form"],
      ],
      ex: [
        ["pick", "We ___ any milk left.", ["don’t have", "haven’t", "not have"], 0, "don’t + have"],
        ["pick", "He ___ answer my call yesterday.", ["didn’t", "doesn’t", "not"], 0, "Past: didn’t."],
        ["pick", "I didn’t say ___.", ["nothing", "anything", "something"], 1, "After a negative: anything."],
        ["pick", "She ___ at home right now.", ["not", "isn’t", "doesn’t"], 1, "be + not: isn’t."],
        ["spot", "My phone not charging properly.", "not charging", "isn't charging", "Add the helping verb."],
        ["spot", "We didn't see nobody there.", "nobody", "anybody", "One negative only."],
        ["spot", "He doesn't wants to come.", "wants", "want", "doesn’t + base form"],
        ["type", "I ___ (not / finish) the book yet.", ["haven't finished", "have not finished", "haven’t finished"], "Present perfect negative."],
        ["order", "I didn't understand anything he said.", "didn’t + base form + anything"],
        ["say", "Make it negative: “I told somebody.”", ["I didn't tell anybody", "I didn't tell anyone", "I did not tell anybody", "I did not tell anyone"], "didn’t + tell + anyone"],
      ],
      talk: "Talk about three things you don’t like, two things you didn’t do last week, and one thing you have never done.",
    },
    {
      id: "question-tags",
      title: "Question tags: isn’t it?",
      goal: "Use the right tag instead of “isn’t it?” for everything",
      wm: "Question Tags, Short Answers",
      intro:
        "A question tag is a short question at the end of a sentence to check or invite agreement: “You’re coming, aren’t you?” Indian English often uses “isn’t it?” or “no?” for everything. In standard English the tag copies the helping verb and the subject, and flips positive and negative.",
      rules: [
        ["Positive sentence → negative tag. Negative sentence → positive tag.", "It’s cold, isn’t it?", "You don’t eat meat, do you?"],
        ["Copy the helping verb and use a pronoun.", "Ravi can swim, can’t he?", "They’ve left, haven’t they?"],
        ["No helping verb? Use do/does/did.", "She lives here, doesn’t she?", "You called him, didn’t you?"],
        ["Special: I am → aren’t I? Let’s → shall we?", "I’m late, aren’t I?", "Let’s go, shall we?"],
      ],
      mistakes: [
        ["You are coming, isn’t it?", "You are coming, aren’t you?", "Copy the verb and subject: aren’t you."],
        ["She works in Pune, isn’t it?", "She works in Pune, doesn’t she?", "No helping verb: doesn’t she."],
        ["He didn’t come, didn’t he?", "He didn’t come, did he?", "Negative sentence, positive tag."],
        ["You know him, no?", "You know him, don’t you?", "Use a proper tag."],
      ],
      ex: [
        ["pick", "You’re from Chennai, ___?", ["isn’t it", "aren’t you", "don’t you"], 1, "are you → aren’t you"],
        ["pick", "He plays cricket, ___?", ["doesn’t he", "isn’t it", "don’t he"], 0, "plays → doesn’t he"],
        ["pick", "They haven’t arrived yet, ___?", ["haven’t they", "have they", "isn’t it"], 1, "Negative → positive tag."],
        ["pick", "You called her yesterday, ___?", ["didn’t you", "don’t you", "isn’t it"], 0, "Past → didn’t you."],
        ["pick", "I’m right, ___?", ["amn’t I", "aren’t I", "isn’t it"], 1, "Special: aren’t I."],
        ["spot", "She can drive, isn't it?", "isn't it", "can't she", "Copy the verb: can’t she."],
        ["spot", "You will help me, isn't it?", "isn't it", "won't you", "will → won’t you"],
        ["spot", "Let's order food, isn't it?", "isn't it", "shall we", "Let’s → shall we"],
        ["type", "The weather is lovely today, ___ it?", ["isn't", "isn’t"], "is → isn’t it"],
        ["order", "You don't like spicy food, do you?", "Negative sentence, positive tag."],
        ["say", "Add the tag: “You live near the station, …”", ["You live near the station don't you"], "live → don’t you"],
      ],
      talk: "Check five facts about the coach’s life using question tags: “You live in…, don’t you?”, “You haven’t…, have you?”.",
    },
    {
      id: "short-answers",
      title: "Short answers: So do I, Neither can I",
      goal: "Reply naturally with “Yes, I do”, “So do I” and “Me neither”",
      wm: "Short Answers; Additions to Remarks",
      intro:
        "Native speakers rarely answer with just “yes” or repeat the whole sentence. They use a short answer with the helping verb: “Do you like it?” – “Yes, I do.” To agree, they say “So do I” (positive) or “Neither do I” (negative).",
      rules: [
        ["Short answer: Yes/No + subject + helping verb.", "Are you ready? – Yes, I am.", "Did she call? – No, she didn’t."],
        ["Agree with a positive: So + helping verb + subject (or “Me too”).", "I love tea. – So do I.", "I’m tired. – So am I."],
        ["Agree with a negative: Neither + helping verb + subject (or “Me neither”).", "I can’t swim. – Neither can I.", "I didn’t go. – Neither did I."],
      ],
      mistakes: [
        ["I don’t like it. – Me too.", "I don’t like it. – Me neither.", "Agreeing with a negative: me neither."],
        ["Do you have a pen? – Yes, I have.", "Yes, I do.", "The question uses “do”, so answer with “do”."],
        ["I am hungry. – So do I.", "So am I.", "Copy the verb: am → so am I."],
        ["She can’t come. – Neither I can.", "Neither can I.", "Verb before the subject."],
      ],
      ex: [
        ["pick", "Do you speak Marathi? – Yes, I ___.", ["speak", "do", "am"], 1, "Yes, I do."],
        ["pick", "I’m so tired. – So ___ I.", ["do", "am", "have"], 1, "am → so am I"],
        ["pick", "I didn’t sleep well. – ___ did I.", ["So", "Neither", "Either"], 1, "Negative → neither."],
        ["pick", "Have you eaten? – No, I ___.", ["don’t", "haven’t", "didn’t"], 1, "have → haven’t"],
        ["pick", "I can’t cook. – ___.", ["Me too", "Me neither", "So can I"], 1, "Negative → me neither."],
        ["spot", "I love old songs. – So I do.", "So I do", "So do I", "Verb before subject: So do I."],
        ["spot", "Is he your brother? – Yes, he does.", "does", "is", "The question uses “is”."],
        ["spot", "I haven't seen it. – Neither I have.", "Neither I have", "Neither have I", "Verb before subject."],
        ["type", "Did you like the food? – Yes, I ___.", ["did"], "did → Yes, I did."],
        ["order", "I went to bed late. So did I.", "past → so did I"],
        ["say", "Agree with: “I don’t like waking up early.”", ["Neither do I", "Me neither", "Me either"], "Negative → Neither do I / Me neither."],
      ],
      talk: "Say five things about yourself, some positive and some negative. After each one, add the reply a friend who agrees would give: “I love mangoes. – So do I.”, “I can’t dance. – Neither can I.”",
    },
  ],
};
