export const unit = {
  n: 9,
  title: "Verb patterns",
  note: "to do or doing, make and let, used to, and the passive",
  lessons: [
    {
      id: "passive",
      title: "Active and passive",
      goal: "Say what was done when the doer doesn’t matter",
      wm: "The Verb: Active and Passive Voice",
      intro:
        "In the active voice, the doer comes first: “Someone stole my bike.” In the passive, the thing that the action happened to comes first: “My bike was stolen.” Use the passive when the doer is unknown, unimportant, or obvious. Form: be + past participle.",
      rules: [
        ["be (in any tense) + past participle.", "English is spoken here.", "The road was repaired last week."],
        ["Add “by” only if the doer matters.", "This book was written by Tagore.", "The meeting has been cancelled."],
        ["Every tense has a passive.", "It is being fixed. (now)", "It will be delivered tomorrow."],
      ],
      mistakes: [
        ["My phone was stole.", "My phone was stolen.", "be + past participle"],
        ["The work is complete by tomorrow.", "The work will be completed by tomorrow.", "Future passive: will be + past participle."],
        ["I was born in 1995 year.", "I was born in 1995.", "Just the year, no “year”."],
        ["This house built in 1950.", "This house was built in 1950.", "Don’t drop “was”."],
      ],
      ex: [
        ["pick", "This temple ___ in the 12th century.", ["built", "was built", "was build"], 1, "Past passive: was built."],
        ["pick", "Rice ___ in many parts of India.", ["grows", "is grown", "is grow"], 1, "Present passive: is grown."],
        ["pick", "Your order ___ tomorrow.", ["will deliver", "will be delivered", "is deliver"], 1, "Future passive."],
        ["pick", "The road ___ at the moment.", ["is being repaired", "is repairing", "being repaired"], 0, "Now: is being repaired."],
        ["pick", "The results have ___ announced.", ["been", "be", "being"], 0, "have been + past participle"],
        ["spot", "The window was broke by the kids.", "broke", "broken", "be + past participle"],
        ["spot", "The meeting has cancelled.", "has cancelled", "has been cancelled", "Passive: has been cancelled."],
        ["spot", "My car stolen last night.", "stolen", "was stolen", "Don’t drop “was”."],
        ["type", "Where ___ you born?", ["were"], "Where were you born?"],
        ["order", "The report will be sent on Monday.", "will + be + past participle"],
        ["say", "Make it passive: “They cancelled the flight.”", ["The flight was cancelled", "The flight was canceled"], "The flight was cancelled."],
      ],
      talk: "Describe your city or a famous building: when it was built, what it is known for, and what is being done there now. Use the passive at least four times.",
    },
    {
      id: "to-or-ing",
      title: "To do or doing?",
      goal: "Know which verbs take “to + verb” and which take “-ing”",
      wm: "The Infinitive and the Gerund",
      intro:
        "When one verb follows another, the second verb is either “to + verb” (I want to go) or “-ing” (I enjoy going). It depends on the first verb, so it has to be learned. Also, after a preposition (in, of, about, for, to in “look forward to”), always use -ing.",
      rules: [
        ["+ to do: want, need, decide, hope, plan, promise, agree, learn, manage, would like.", "I decided to leave.", "She hopes to see you."],
        ["+ doing: enjoy, finish, avoid, mind, suggest, keep, practise, consider, can’t help.", "I enjoy cooking.", "He suggested going by train."],
        ["After a preposition: -ing.", "I’m interested in learning Spanish.", "I’m looking forward to meeting you."],
      ],
      mistakes: [
        ["I look forward to meet you.", "I look forward to meeting you.", "Here “to” is a preposition, so -ing."],
        ["I enjoy to read.", "I enjoy reading.", "enjoy + -ing"],
        ["He suggested to go.", "He suggested going.", "suggest + -ing"],
        ["I am used to wake up early.", "I am used to waking up early.", "be used to + -ing"],
      ],
      ex: [
        ["pick", "I want ___ a new language.", ["learning", "to learn", "learn"], 1, "want + to"],
        ["pick", "Have you finished ___ the report?", ["to write", "writing", "write"], 1, "finish + -ing"],
        ["pick", "We’re thinking of ___ a car.", ["to buy", "buying", "buy"], 1, "After a preposition: -ing."],
        ["pick", "She promised ___ on time.", ["to be", "being", "be"], 0, "promise + to"],
        ["pick", "Would you mind ___ the door?", ["to close", "closing", "close"], 1, "mind + -ing"],
        ["spot", "I am looking forward to hear from you.", "hear", "hearing", "look forward to + -ing"],
        ["spot", "She avoids to eat sugar.", "to eat", "eating", "avoid + -ing"],
        ["spot", "They agreed helping us.", "helping", "to help", "agree + to"],
        ["type", "I really enjoy ___ (travel) alone.", ["travelling", "traveling"], "enjoy + -ing"],
        ["order", "I'm looking forward to seeing you soon.", "look forward to + -ing"],
        ["say", "Correct this: “I look forward to work with you.”", ["I look forward to working with you", "I am looking forward to working with you"], "look forward to + -ing"],
      ],
      talk: "Talk about what you enjoy doing, what you want to do this year, and what you’re looking forward to. Use at least three -ing and three “to” forms.",
    },
    {
      id: "make-let-help",
      title: "Make, let, help, get",
      goal: "Use make/let + person + verb without “to”",
      wm: "The Infinitive without “to”",
      intro:
        "Some verbs take a person and then a verb without “to”: make someone do something, let someone do something. “Help” works with or without “to”. “Get” needs “to”. Hindi thinking often adds “to” after make and let, which sounds wrong in English.",
      rules: [
        ["make + person + base form (force or cause).", "My boss made me stay late.", "That film made me cry."],
        ["let + person + base form (allow).", "Let me explain.", "My parents let me travel alone."],
        ["help + person + (to) verb. get + person + to verb.", "She helped me (to) move.", "I got him to fix it."],
      ],
      mistakes: [
        ["He made me to wait.", "He made me wait.", "make + person + base form"],
        ["Let me to check.", "Let me check.", "let + base form"],
        ["Let us discuss about it.", "Let’s discuss it.", "No “about” after discuss."],
        ["I got him fix my laptop.", "I got him to fix my laptop.", "get + person + to"],
      ],
      ex: [
        ["pick", "Let me ___ you something.", ["show", "to show", "showing"], 0, "let + base form"],
        ["pick", "The teacher made us ___ the essay again.", ["write", "to write", "writing"], 0, "make + base form"],
        ["pick", "I got my brother ___ me to the airport.", ["drive", "to drive", "driving"], 1, "get + to"],
        ["pick", "Can you help me ___ this box?", ["carry", "carrying", "carried"], 0, "help + (to) verb"],
        ["spot", "My father didn't let me to go.", "to go", "go", "let + base form"],
        ["spot", "The news made her to smile.", "to smile", "smile", "make + base form"],
        ["spot", "Let us discuss about the plan.", "discuss about", "discuss", "No “about” after discuss."],
        ["type", "Don’t make me ___ (laugh)!", ["laugh"], "make + base form"],
        ["order", "Please let me know if you need anything.", "let + me + know"],
        ["say", "Correct this: “Let me to explain.”", ["Let me explain"], "let + base form"],
      ],
      talk: "Talk about your childhood: what your parents let you do, what they made you do, and who helped you learn something important.",
    },
    {
      id: "used-to",
      title: "Used to and would",
      goal: "Talk about old habits, and don’t confuse “used to” with “be used to”",
      wm: "Verb Patterns",
      intro:
        "“Used to + verb” describes past habits or states that are no longer true: “I used to live in Kolkata.” It is different from “be used to + -ing”, which means “be familiar with”: “I’m used to working late.” Many learners say “I am used to go” when they mean “I usually go”.",
      rules: [
        ["used to + base form = in the past, but not now.", "I used to play football every day.", "There used to be a cinema here."],
        ["Negative and question: didn’t use to / Did you use to…?", "I didn’t use to like coffee.", "Did you use to live here?"],
        ["be / get used to + -ing = be familiar with.", "I’m used to the noise.", "She’s getting used to living alone."],
        ["For present habits, use “usually”, not “used to”.", "I usually go for a walk after dinner.", "We usually eat at home."],
      ],
      mistakes: [
        ["I am used to go for a walk daily.", "I usually go for a walk every day.", "For a present habit, say “usually”."],
        ["I use to live in Patna.", "I used to live in Patna.", "Write and say “used to” (sounds like “yoos-tuh”)."],
        ["Did you used to smoke?", "Did you use to smoke?", "After did: use."],
        ["I’m used to wake up early.", "I’m used to waking up early.", "be used to + -ing"],
      ],
      ex: [
        ["pick", "I ___ in a hostel when I was in college.", ["used to live", "am used to live", "use to living"], 0, "Past habit: used to live."],
        ["pick", "I ___ go to the gym on weekends. (now)", ["used to", "usually", "am used to"], 1, "Present habit: usually."],
        ["pick", "It took time, but now I’m used to ___ in the city.", ["drive", "driving", "drove"], 1, "be used to + -ing"],
        ["pick", "Did you ___ play any sport?", ["used to", "use to", "using to"], 1, "did + use to"],
        ["spot", "I am used to go to office by metro.", "am used to go", "usually go", "Present habit: usually go."],
        ["spot", "She didn't used to eat spicy food.", "used", "use", "didn’t + use to"],
        ["spot", "He is getting used to work at night.", "work", "working", "get used to + -ing"],
        ["type", "There ___ to be a big tree in front of our house.", ["used"], "Past state: used to be."],
        ["order", "I used to be very shy in school.", "used to + base form"],
        ["say", "Correct this: “I am used to drink tea every morning.”", ["I usually drink tea every morning"], "Present habit: I usually drink…"],
      ],
      talk: "Compare your life ten years ago and now: what you used to do, what you usually do now, and something you are still getting used to.",
    },
  ],
};
