export const unit = {
  n: 12,
  title: "Correct usage",
  note: "Agreement, confusing words, and habits to unlearn",
  lessons: [
    {
      id: "agreement",
      title: "One of my friends is",
      goal: "Match the verb with the real subject",
      wm: "Agreement of the Verb with the Subject",
      intro:
        "The verb must agree with its subject: singular subject, singular verb. Trouble starts when other words come between them (“The list of items are…”) or with words like each, everyone, one of, and the number of. Find the real subject, then choose the verb.",
      rules: [
        ["Find the main noun. Words after “of” don’t change it.", "The price of vegetables is high.", "One of my friends lives in Dubai."],
        ["each, every, everyone, somebody, nobody → singular.", "Everyone is here.", "Each student has a laptop."],
        ["“The number of” → singular. “A number of” (= many) → plural.", "The number of cars is growing.", "A number of people were waiting."],
        ["Two subjects joined by “and” → plural. With “or / nor”, match the nearer one.", "My brother and sister live abroad.", "Neither the manager nor the staff were told."],
      ],
      mistakes: [
        ["One of my friends are coming.", "One of my friends is coming.", "The subject is “one”."],
        ["Everyone have to sign.", "Everyone has to sign.", "everyone → singular."],
        ["The quality of these products are good.", "The quality of these products is good.", "The subject is “quality”."],
        ["The number of students have increased.", "The number of students has increased.", "“The number” → singular."],
      ],
      ex: [
        ["pick", "One of the lights ___ not working.", ["is", "are"], 0, "The subject is “one”."],
        ["pick", "Every child ___ a gift.", ["get", "gets"], 1, "every → singular"],
        ["pick", "The list of names ___ on the wall.", ["is", "are"], 0, "The subject is “list”."],
        ["pick", "A number of problems ___ come up.", ["has", "have"], 1, "A number of = many → plural."],
        ["pick", "Rice and dal ___ my favourite meal.", ["is", "are"], 0, "One dish thought of as one thing: is."],
        ["spot", "Each of the rooms have a balcony.", "have", "has", "each → singular"],
        ["spot", "Nobody know the answer.", "know", "knows", "nobody → singular"],
        ["spot", "The cost of these phones are too high.", "are", "is", "The subject is “cost”."],
        ["type", "Everybody ___ (want) to be happy.", ["wants"], "everybody → wants"],
        ["order", "One of my colleagues is from Assam.", "One of + plural + is"],
        ["say", "Correct this: “One of my cousin are a pilot.”", ["One of my cousins is a pilot"], "One of my cousins is…"],
      ],
      talk: "Talk about your team or class: how many people there are, what everyone does, and describe one of your friends there.",
    },
    {
      id: "confusing-pairs",
      title: "Say or tell, make or do",
      goal: "Choose between words that Indian speakers often mix up",
      wm: "Correct Usage: Verbs",
      intro:
        "Some pairs of words look similar but are used differently: say and tell, speak and talk, borrow and lend, bring and take, make and do, lose and miss. Knowing the pattern for each pair makes your English sound much more natural.",
      rules: [
        ["say something; tell someone something.", "She said hello.", "Tell me the truth."],
        ["borrow FROM someone; lend TO someone.", "Can I borrow your pen?", "Can you lend me your pen?"],
        ["make = create or produce; do = work, tasks, activities.", "make a cake, make a mistake, make a decision", "do homework, do the dishes, do a favour"],
        ["bring = to here; take = to there.", "Bring your laptop to my desk.", "Take this file to the manager."],
      ],
      mistakes: [
        ["Can you borrow me your book?", "Can you lend me your book?", "lend TO someone."],
        ["I did a mistake.", "I made a mistake.", "make a mistake"],
        ["He told that he was busy.", "He said that he was busy.", "tell needs a person."],
        ["I missed my wallet.", "I lost my wallet.", "lose = can’t find; miss = didn’t catch or feel sad without."],
        ["Let’s do a plan.", "Let’s make a plan.", "make a plan"],
      ],
      ex: [
        ["pick", "Could you ___ me some money until Monday?", ["borrow", "lend"], 1, "lend TO someone"],
        ["pick", "She ___ me a funny story.", ["said", "told"], 1, "tell + person"],
        ["pick", "Have you ___ your homework?", ["made", "done"], 1, "do homework"],
        ["pick", "I need to ___ a decision soon.", ["make", "do"], 0, "make a decision"],
        ["pick", "Hurry, or we’ll ___ the train!", ["lose", "miss"], 1, "miss a train"],
        ["spot", "Can I lend your charger for a minute?", "lend", "borrow", "borrow FROM someone"],
        ["spot", "Everyone does mistakes.", "does", "makes", "make mistakes"],
        ["spot", "He said me to wait outside.", "said me", "told me", "tell + person"],
        ["type", "Can you do me a ___? (favour / help)", ["favour", "favor"], "do someone a favour"],
        ["order", "Please take these books back to the library.", "take = to there"],
        ["say", "Correct this: “Can you borrow me your bike?”", ["Can you lend me your bike", "Can I borrow your bike"], "Can you lend me… / Can I borrow…"],
      ],
      talk: "Tell the coach about a time you borrowed or lent something, a mistake you made, and something someone told you that you still remember.",
    },
    {
      id: "indianisms",
      title: "Habits to unlearn",
      goal: "Replace common Indian-English phrases with international ones",
      wm: "Correct Usage: Idioms",
      intro:
        "Indian English is a real variety of English, and many of its phrases are fine at home. But some of them confuse people from other countries or sound old-fashioned. Knowing the international version lets you choose: “prepone”, “passed out”, “cousin brother”, “out of station”, “do the needful” and “What is your good name?”.",
      rules: [
        ["prepone → bring forward / move earlier.", "Can we bring the meeting forward to 10?", "The exam was moved earlier."],
        ["passed out (of college) → graduated. (“Passed out” means fainted!)", "I graduated in 2018.", "She graduated from IIT."],
        ["cousin brother / sister → cousin. out of station → out of town / away.", "My cousin is visiting.", "I’m out of town this week."],
        ["What is your good name? → May I know your name? / What’s your name?", "Sorry, what was your name?", "Could I have your name, please?"],
      ],
      mistakes: [
        ["Can we prepone the call?", "Can we move the call earlier?", "“Prepone” is only understood in India."],
        ["I passed out from college in 2019.", "I graduated from college in 2019.", "“Passed out” means fainted."],
        ["He is my cousin brother.", "He is my cousin.", "“Cousin” already covers it."],
        ["I am out of station till Monday.", "I’m out of town until Monday.", "Say “out of town” or “away”."],
        ["Please do the needful.", "Please could you process this? (say the exact action)", "Say what you actually need."],
      ],
      ex: [
        ["pick", "I ___ from Delhi University in 2016.", ["passed out", "graduated", "passed away"], 1, "graduated"],
        ["pick", "Can we ___ the meeting to 9 am?", ["prepone", "bring forward", "pre-shift"], 1, "bring forward"],
        ["pick", "My ___ is getting married next month.", ["cousin", "cousin brother", "cousin-sister"], 0, "cousin"],
        ["pick", "I’ll be ___ next week, visiting my parents.", ["out of station", "out of town", "outstation"], 1, "out of town"],
        ["pick", "Hello, ___?", ["what is your good name", "may I know your name", "your name please what"], 1, "May I know your name?"],
        ["spot", "My cousin sister lives in Canada.", "cousin sister", "cousin", "Just “cousin”."],
        ["spot", "We need to prepone the launch.", "prepone", "bring forward", "bring forward"],
        ["spot", "I passed out from engineering college last year.", "passed out", "graduated", "graduated"],
        ["type", "I’m out of ___ for two days, so call me on my mobile.", ["town"], "out of town"],
        ["order", "Could we move the meeting to an earlier time?", "The international way to say “prepone”."],
        ["say", "Say it the international way: “I passed out in 2015.”", ["I graduated in 2015"], "I graduated in 2015."],
      ],
      talk: "Introduce your education and family, and explain a change in your schedule, without using prepone, passed out, cousin brother or out of station.",
    },
    {
      id: "fixed-phrases",
      title: "Small phrases, said right",
      goal: "Use everyday phrases the way native speakers say them",
      wm: "Idioms and Idiomatic Expressions",
      intro:
        "Much of fluent English is fixed phrases: “on the way”, “in time”, “at the end”, “take a photo”, “by mistake”. Getting one small word wrong (“in the way”, “give an exam”) is enough to sound unnatural. Here are the everyday ones Indian speakers most often mix up.",
      rules: [
        ["take an exam (write it); pass / fail an exam; take a photo, take a break.", "I’m taking my driving test on Monday.", "Let’s take a photo."],
        ["on time = punctual; in time = early enough.", "The train was on time.", "We got there in time to see the start."],
        ["by mistake, by chance, on purpose, on the way, in a hurry.", "I deleted it by mistake.", "I’ll pick up milk on the way."],
        ["at the end (of something) vs in the end (finally).", "at the end of the film", "In the end, we stayed home."],
      ],
      mistakes: [
        ["I gave my exam yesterday.", "I took my exam yesterday.", "In international English you take an exam; examiners give it."],
        ["Click a photo of us.", "Take a photo of us.", "take a photo"],
        ["I did it in mistake.", "I did it by mistake.", "by mistake"],
        ["I am on the way to reach.", "I’m on my way.", "Just “I’m on my way”."],
        ["She came at time.", "She came on time.", "on time"],
      ],
      ex: [
        ["pick", "Can you ___ a picture of me here?", ["click", "take", "do"], 1, "take a picture"],
        ["pick", "I sent the email to the wrong person ___.", ["by mistake", "in mistake", "with mistake"], 0, "by mistake"],
        ["pick", "The meeting started exactly ___.", ["in time", "on time", "at time"], 1, "on time = at the planned time"],
        ["pick", "I’m ___. I’ll be there in ten minutes.", ["on my way", "in the way", "on the way to reach"], 0, "on my way"],
        ["pick", "She is ___ her final exams next month.", ["giving", "taking", "doing"], 1, "take exams"],
        ["spot", "I will give the exam next week.", "give", "take", "take an exam"],
        ["spot", "He broke the glass in purpose.", "in purpose", "on purpose", "on purpose"],
        ["spot", "At the end, we decided to stay home.", "At the end", "In the end", "Finally = in the end."],
        ["type", "We reached the cinema just ___ time for the film.", ["in"], "in time = early enough"],
        ["order", "Let's take a short break and get some tea.", "take a break"],
        ["say", "Correct this: “Please click our photo.”", ["Please take our photo", "Please take a photo of us", "Could you take our photo", "Could you take a photo of us"], "Please take a photo of us."],
      ],
      talk: "Describe your last exam or interview day from start to end: whether you were on time, what happened on the way, and how it went in the end.",
    },
  ],
};
