export const unit = {
  n: 5,
  title: "Present and past",
  note: "The tenses you use in every conversation",
  lessons: [
    {
      id: "be-have-do",
      title: "Be, have, do: the helpers",
      goal: "Use am/is/are, has/have and do/does correctly",
      wm: "The Verb: Auxiliaries",
      intro:
        "Three verbs do most of the work in English: be, have and do. They are main verbs (“I am tired”, “I have a car”, “I do yoga”) and also helping verbs that build questions, negatives and tenses. Getting their forms right fixes a huge number of mistakes at once.",
      rules: [
        ["be: I am, you/we/they are, he/she/it is.", "They are late.", "The office is closed."],
        ["have: I/you/we/they have, he/she/it has.", "She has two kids.", "We have a meeting."],
        ["do: I/you/we/they do, he/she/it does. Use it for questions and negatives in the simple present.", "Do you work here?", "He doesn’t eat eggs."],
      ],
      mistakes: [
        ["He have a new car.", "He has a new car.", "he/she/it → has"],
        ["She don’t know.", "She doesn’t know.", "he/she/it → doesn’t"],
        ["They was at home.", "They were at home.", "they → were"],
        ["Does he has a pen?", "Does he have a pen?", "After does, the verb goes back to the base form."],
      ],
      ex: [
        ["pick", "My parents ___ in Nagpur.", ["is", "are", "am"], 1, "Plural: are."],
        ["pick", "Rohan ___ a lot of friends.", ["have", "has", "having"], 1, "he → has"],
        ["pick", "___ your sister work in IT?", ["Do", "Does", "Is"], 1, "she → does"],
        ["pick", "We ___ at the airport when you called.", ["was", "were", "are"], 1, "we → were"],
        ["pick", "Does she ___ a car?", ["has", "have", "having"], 1, "After does: base form have."],
        ["spot", "My boss don't like long emails.", "don't", "doesn't", "he → doesn’t"],
        ["spot", "She have two brothers.", "have", "has", "she → has"],
        ["spot", "Does he knows the address?", "knows", "know", "After does: base form."],
        ["type", "___ you have any brothers or sisters?", ["Do"], "you → do"],
        ["order", "He doesn't have much time today.", "doesn’t + have"],
        ["say", "Make it negative: “She has a laptop.”", ["She doesn't have a laptop", "She does not have a laptop"], "doesn’t + have"],
      ],
      talk: "Describe a friend or family member: what they have, what they do and don’t do every day, and where they are right now.",
    },
    {
      id: "present-simple",
      title: "Present simple: habits and facts",
      goal: "Talk about routines, and never forget the -s",
      wm: "Tenses: Simple Present",
      intro:
        "The present simple is for habits, routines, facts and timetables: “I get up at seven”, “Water boils at 100°C”. With he, she and it the verb takes -s: “She works”. This little -s is the most forgotten ending in English, so train your ear for it.",
      rules: [
        ["he / she / it + verb-s (or -es).", "She works in a bank.", "He watches the news every night."],
        ["Negative: don’t / doesn’t + base verb.", "I don’t drink coffee.", "It doesn’t matter."],
        ["Use it with always, usually, often, sometimes, never, every day.", "We usually eat at eight.", "He never calls me."],
      ],
      mistakes: [
        ["My father work in a bank.", "My father works in a bank.", "he → works"],
        ["She go to gym daily.", "She goes to the gym every day.", "she → goes. “Every day” is more natural than “daily” in speech."],
        ["He doesn’t likes it.", "He doesn’t like it.", "After doesn’t: base form."],
        ["I am going to office daily.", "I go to the office every day.", "Habits use the simple present, not -ing."],
      ],
      ex: [
        ["pick", "My sister ___ in Hyderabad.", ["live", "lives", "living"], 1, "she → lives"],
        ["pick", "I usually ___ to work by bus.", ["go", "goes", "am going"], 0, "Habit, with I: go."],
        ["pick", "The shop ___ at ten every morning.", ["open", "opens", "is opening"], 1, "Timetable: opens."],
        ["pick", "He ___ tea after dinner.", ["don’t drink", "doesn’t drink", "doesn’t drinks"], 1, "doesn’t + base form"],
        ["pick", "Water ___ at 100 degrees.", ["boil", "boils", "is boiling"], 1, "A fact: boils."],
        ["spot", "My mother cook very well.", "cook", "cooks", "she → cooks"],
        ["spot", "Every Sunday I am playing cricket with my friends.", "am playing", "play", "Habits use the simple present."],
        ["spot", "She doesn't speaks Hindi.", "speaks", "speak", "doesn’t + base form"],
        ["type", "He ___ (watch) a movie every Friday night.", ["watches"], "watch → watches"],
        ["order", "My brother never gets up before nine.", "never + verb-s"],
        ["say", "Say it about your friend: “I play chess every evening.” → “He…”", ["He plays chess every evening"], "he → plays"],
      ],
      talk: "Describe the daily routine of someone in your family. Use he or she in every sentence and listen for your -s: works, goes, watches.",
    },
    {
      id: "present-continuous",
      title: "Present continuous, and when not to use it",
      goal: "Use -ing for now, and stop saying “I am having a car”",
      wm: "Tenses: Present Continuous",
      intro:
        "The present continuous (am/is/are + -ing) is for actions happening now or around now, and for plans. But some verbs describe states, not actions, and almost never take -ing: know, understand, like, want, need, believe, own, have (= own). “I am having a doubt” and “I am knowing him” are classic Indian-English mistakes.",
      rules: [
        ["Now or around now: am/is/are + -ing.", "I’m talking to a client right now.", "She’s studying for her exams this month."],
        ["Future plans: am/is/are + -ing.", "We’re meeting them on Friday.", "I’m flying to Kochi tomorrow."],
        ["State verbs stay simple: know, understand, believe, like, love, hate, want, need, prefer, mean, own, belong, seem.", "I know him well.", "Do you understand?"],
        ["“have” = own is simple; “have” = eat, take, enjoy can be -ing.", "I have a question. / I have a car.", "We’re having dinner. / We’re having fun."],
      ],
      mistakes: [
        ["I am having a doubt.", "I have a question.", "“Have” for owning is not used with -ing. And “doubt” means you don’t believe something; for asking, say “question”."],
        ["I am knowing him since college.", "I have known him since college.", "“Know” doesn’t take -ing."],
        ["She is wanting to leave.", "She wants to leave.", "“Want” doesn’t take -ing."],
        ["I am understanding now.", "I understand now.", "“Understand” doesn’t take -ing."],
      ],
      ex: [
        ["pick", "Can I call you back? I ___ right now.", ["drive", "am driving", "drives"], 1, "Happening now: am driving."],
        ["pick", "I ___ what you mean.", ["am understanding", "understand", "understanding"], 1, "State verb: understand."],
        ["pick", "She ___ a new flat in Pune.", ["is having", "has", "having"], 1, "Owning: has."],
        ["pick", "We ___ lunch. Can we talk later?", ["have", "are having", "has"], 1, "Having = eating: are having."],
        ["pick", "This bag ___ to my sister.", ["belongs", "is belonging", "belong"], 0, "State verb: belongs."],
        ["spot", "I am having one small doubt about the report.", "am having one small doubt", "have a quick question", "Say “I have a question”."],
        ["spot", "He is liking his new job.", "is liking", "likes", "State verb: likes."],
        ["spot", "Look! It rains.", "rains", "is raining", "Happening now: is raining."],
        ["type", "What ___ you doing this weekend? (plan)", ["are"], "Plans: What are you doing…?"],
        ["order", "I'm working from home this week.", "Around now: am + -ing."],
        ["say", "Correct this: “I am having a doubt about this.”", ["I have a question about this", "I have a doubt about this"], "“Have” (owning) doesn’t take -ing. “Question” is clearer than “doubt”."],
      ],
      talk: "Tell the coach what you’re doing these days (your projects, what you’re learning) and what you’re doing this weekend. Then say two things you know or want, without -ing.",
    },
    {
      id: "past-simple",
      title: "Past simple: what happened",
      goal: "Talk about finished events with the right past forms",
      wm: "Tenses: Simple Past; Irregular Verbs",
      intro:
        "Use the past simple for finished actions at a finished time: yesterday, last week, in 2019, two days ago. Regular verbs add -ed, but the most common verbs are irregular (go → went, buy → bought). In questions and negatives, “did” carries the past, so the main verb goes back to its base form.",
      rules: [
        ["Regular: add -ed. Irregular: learn the form.", "I watched a film.", "We went to Goa and bought gifts."],
        ["Negative: didn’t + base form.", "I didn’t see him.", "She didn’t go."],
        ["Question: did + subject + base form.", "Did you call her?", "Where did you go?"],
      ],
      mistakes: [
        ["I didn’t went there.", "I didn’t go there.", "After didn’t: base form."],
        ["Did you ate lunch?", "Did you eat lunch?", "After did: base form."],
        ["Yesterday I go to the market.", "Yesterday I went to the market.", "Finished time: past form."],
        ["He buyed a car.", "He bought a car.", "buy → bought (irregular)"],
      ],
      ex: [
        ["pick", "We ___ a great movie last night.", ["see", "saw", "seen"], 1, "see → saw"],
        ["pick", "I ___ her yesterday.", ["didn’t meet", "didn’t met", "not met"], 0, "didn’t + base form"],
        ["pick", "___ you finish the work on time?", ["Do", "Did", "Have"], 1, "Past question: did."],
        ["pick", "She ___ me a message an hour ago.", ["send", "sended", "sent"], 2, "send → sent"],
        ["pick", "Where did you ___ your holiday?", ["spent", "spend", "spending"], 1, "did + base form"],
        ["spot", "He didn't told me anything.", "told", "tell", "didn’t + base form"],
        ["spot", "Last year we travel to Sikkim.", "travel", "travelled", "Finished time: past form."],
        ["spot", "Did she came to the office today?", "came", "come", "did + base form"],
        ["type", "I ___ (think) about you yesterday.", ["thought"], "think → thought"],
        ["order", "What did you have for dinner?", "What + did + you + base form"],
        ["say", "Make it negative: “I went to the party.”", ["I didn't go to the party", "I did not go to the party"], "didn’t + go"],
      ],
      talk: "Tell the coach about last weekend from morning to night. Use the past in every sentence: I woke up, I went, I met, I didn’t….",
    },
    {
      id: "past-continuous",
      title: "Past continuous: what was happening",
      goal: "Set the scene of a story, and interrupt it",
      wm: "Tenses: Past Continuous",
      intro:
        "The past continuous (was/were + -ing) describes an action in progress at a moment in the past: “At 9 pm I was cooking.” It’s perfect for the background of a story. A short past-simple action often interrupts it: “I was cooking when the lights went out.”",
      rules: [
        ["was/were + -ing for an action in progress in the past.", "At eight I was driving home.", "They were watching TV."],
        ["Long action (was -ing) + when + short action (past simple).", "I was sleeping when you called.", "She was walking home when it started to rain."],
        ["while + two long actions at the same time.", "While I was cooking, he was cleaning.", "We were talking while they were eating."],
      ],
      mistakes: [
        ["When you called, I slept.", "When you called, I was sleeping.", "The long background action takes was + -ing."],
        ["I was knowing the answer.", "I knew the answer.", "State verbs don’t take -ing, in the past either."],
        ["They was playing outside.", "They were playing outside.", "they → were"],
        ["While I cooked, the phone was ringing.", "While I was cooking, the phone rang.", "Long action: was -ing. Short action: past simple."],
      ],
      ex: [
        ["pick", "I ___ a shower when the doorbell rang.", ["took", "was taking", "am taking"], 1, "The long action: was taking."],
        ["pick", "What ___ you doing at ten last night?", ["was", "were", "did"], 1, "you → were"],
        ["pick", "She was reading when the power ___.", ["went out", "was going out", "goes out"], 0, "The short action: went out."],
        ["pick", "While we ___ dinner, it started to rain.", ["had", "were having", "have"], 1, "Long action: were having."],
        ["spot", "When he entered, we watched a film.", "watched", "were watching", "Background action: were watching."],
        ["spot", "The kids was sleeping when we arrived.", "was", "were", "kids → were"],
        ["spot", "I was driving when I was seeing the accident.", "was seeing", "saw", "The short action: saw."],
        ["type", "It ___ (rain) when we left the house.", ["was raining"], "Background: was raining."],
        ["order", "I was waiting for the bus when I saw her.", "was + -ing … when + past simple"],
        ["say", "Join with “when”: “I was cooking. My friend called.”", ["I was cooking when my friend called"], "Long action + when + short action."],
      ],
      talk: "Tell a short story about something unexpected: what was happening, and then what happened. Use “I was … when …” at least twice.",
    },
  ],
};
