export const unit = {
  n: 3,
  title: "Pronouns",
  note: "I or me, myself, this and that, who and which, some and any",
  lessons: [
    {
      id: "i-me",
      title: "I or me, he or him",
      goal: "Use subject and object pronouns correctly, even in pairs",
      wm: "Personal Pronouns",
      intro:
        "Pronouns change their form: I/me, he/him, she/her, we/us, they/them. The first form does the action (subject). The second form receives it or comes after a preposition (object). Mistakes usually happen when there are two people: “me and my friend went” sounds informal and is wrong in careful English.",
      rules: [
        ["Subject (before the verb): I, he, she, we, they.", "She called me.", "We are late."],
        ["Object (after the verb or a preposition): me, him, her, us, them.", "Call him later.", "This is for them."],
        ["With two people, test each one alone. Put yourself last.", "My friend and I went out. (I went out.)", "He invited my wife and me. (He invited me.)"],
      ],
      mistakes: [
        ["Me and my friend went to Goa.", "My friend and I went to Goa.", "Subject: I. And put yourself last."],
        ["Between you and I, he is wrong.", "Between you and me, he is wrong.", "After a preposition use “me”."],
        ["He told to me that he was busy.", "He told me that he was busy.", "“Tell” takes the person directly: tell me."],
        ["Him and his wife are coming.", "He and his wife are coming.", "Subject: he."],
      ],
      ex: [
        ["pick", "My sister and ___ are twins.", ["me", "I", "myself"], 1, "Subject: I are twins → my sister and I."],
        ["pick", "The manager called Ravi and ___.", ["I", "me", "myself"], 1, "Object: called me."],
        ["pick", "This gift is from ___.", ["we", "us", "our"], 1, "After a preposition: us."],
        ["pick", "___ and I will handle it.", ["Him", "He", "His"], 1, "Subject: he."],
        ["spot", "Me and Anil are working on this project.", "Me and Anil", "Anil and I", "Subject: Anil and I."],
        ["spot", "Please send the report to Neha and I.", "I", "me", "After “to”: me."],
        ["spot", "Can you share it with she?", "she", "her", "After “with”: her."],
        ["type", "Let ___ help you with that bag. (I / me)", ["me"], "let me"],
        ["order", "My wife and I love old films.", "Other person first, then “I”."],
        ["say", "Correct this: “Me and my brother play cricket on Sundays.”", ["My brother and I play cricket on Sundays"], "Subject: my brother and I."],
      ],
      talk: "Tell the coach about something you did recently with a friend or family member. Use “my friend and I” and “with him” or “with her”.",
    },
    {
      id: "myself",
      title: "Myself, yourself: only when needed",
      goal: "Stop saying “Myself Aditya” and use -self words correctly",
      wm: "Reflexive and Emphatic Pronouns",
      intro:
        "Words like myself, yourself and themselves are used when the subject and the object are the same person (“I hurt myself”), or to add emphasis (“I did it myself”). They can’t replace “I” or “me”. “Myself Aditya” is one of the most noticed Indian-English habits: just say “I’m Aditya”.",
      rules: [
        ["Subject and object are the same person.", "She taught herself French.", "Help yourself to some tea."],
        ["For emphasis: “I did it on my own.”", "I made the cake myself.", "The CEO herself replied."],
        ["“by myself” means alone.", "I live by myself.", "He finished it by himself."],
        ["Don’t use them instead of I or me.", "My name is Aditya. / I’m Aditya.", "Please contact Priya or me."],
      ],
      mistakes: [
        ["Myself Aditya, from Pune.", "I’m Aditya, from Pune.", "Introduce yourself with “I’m” or “My name is”."],
        ["Please contact myself for details.", "Please contact me for details.", "“Myself” can’t replace “me”."],
        ["We enjoyed a lot.", "We enjoyed ourselves a lot.", "“Enjoy” needs an object: enjoy it, or enjoy ourselves."],
        ["He himself he did it.", "He did it himself.", "Use the -self word once, usually at the end."],
      ],
      ex: [
        ["pick", "Hi, ___ Karan. I work in sales.", ["myself", "I’m", "me"], 1, "Introduce yourself: I’m Karan."],
        ["pick", "Did you all enjoy ___ at the party?", ["yourself", "yourselves", "you"], 1, "You all → yourselves."],
        ["pick", "She cut ___ while cooking.", ["her", "herself", "she"], 1, "Same person: she cut herself."],
        ["pick", "My brother and ___ will be there.", ["myself", "I", "me"], 1, "Subject: I."],
        ["pick", "They built the house ___.", ["themself", "theirselves", "themselves"], 2, "They → themselves."],
        ["spot", "Myself Neha, and I handle marketing.", "Myself Neha", "I’m Neha", "Introduce yourself: I’m Neha."],
        ["spot", "Please send the details to myself.", "myself", "me", "After “to”: me."],
        ["spot", "We really enjoyed at the wedding.", "enjoyed", "enjoyed ourselves", "“Enjoy” needs an object."],
        ["type", "Don’t worry, I can do it by ___.", ["myself"], "by myself = alone"],
        ["order", "I taught myself to cook.", "Same person: I … myself."],
        ["say", "Introduce yourself correctly. Start with: “Hi, I’m…” and say your name.", ["Hi I am*", "Hello I am*", "Hi my name is*", "Hello my name is*"], "Hi, I’m + name. Never “Myself + name”."],
      ],
      talk: "Introduce yourself as if you are joining a new team: your name, your work, where you are from, and one thing you taught yourself.",
    },
    {
      id: "this-that",
      title: "This, that, these, those, one",
      goal: "Point to things near and far, one or many",
      wm: "Demonstrative Pronouns",
      intro:
        "“This” and “these” are for things near you; “that” and “those” for things further away. This/that for one thing, these/those for more than one. To avoid repeating a noun, use “one” or “ones”: “I like the blue one.”",
      rules: [
        ["Near: this (one), these (many).", "This coffee is hot.", "These shoes are new."],
        ["Far: that (one), those (many).", "Who is that man?", "Those days were fun."],
        ["Use one/ones so you don’t repeat the noun.", "I don’t like this shirt. Show me that one.", "The red ones are cheaper."],
      ],
      mistakes: [
        ["These type of people…", "This type of person… / These types of people…", "Match the number: this type, these types."],
        ["This shoes are comfortable.", "These shoes are comfortable.", "Shoes are plural: these."],
        ["I want the blue.", "I want the blue one.", "After an adjective, add “one”."],
        ["That days were difficult.", "Those days were difficult.", "Days are plural: those."],
      ],
      ex: [
        ["pick", "___ mangoes are very sweet.", ["This", "These", "That"], 1, "Plural and near: these."],
        ["pick", "Who were ___ people at the gate?", ["that", "those", "this"], 1, "Plural and far: those."],
        ["pick", "I prefer the black ___.", ["one", "ones", "—"], 0, "One thing: the black one."],
        ["pick", "The small cups are cheap, but the big ___ are better.", ["one", "ones", "them"], 1, "Plural: ones."],
        ["spot", "This kind of mistakes are common.", "This kind of mistakes are", "These kinds of mistakes are", "Match the number: these kinds…are."],
        ["spot", "Can you pass me that books?", "that", "those", "Books are plural: those."],
        ["spot", "I don't like the green, I want the red.", "the red", "the red one", "After an adjective add “one”."],
        ["type", "Look at ___ stars up there! (this / these / those)", ["those"], "Plural and far away: those."],
        ["order", "These are my old school friends.", "Plural and near: these."],
        ["say", "Correct this: “This clothes are very expensive.”", ["These clothes are very expensive"], "Clothes are plural: these."],
      ],
      talk: "Imagine you are in a shop. Ask about three things near you and far away. Use this, that, these, those, and “the blue one”.",
    },
    {
      id: "who-which",
      title: "Who, which, that, whose",
      goal: "Join sentences with who, which, that and whose",
      wm: "Relative Pronouns",
      intro:
        "Relative pronouns let you describe someone or something inside one sentence: “The man who called you is my boss.” Use “who” for people, “which” for things, “that” for both, and “whose” to show belonging.",
      rules: [
        ["who for people, which for things, that for either.", "The girl who sings is my niece.", "The phone that I bought is fast."],
        ["whose = belonging to whom.", "That’s the man whose car was stolen.", "I have a friend whose father is a pilot."],
        ["Don’t repeat the pronoun after who/which.", "The book which I read was long. (not “which I read it”)", "The lady who lives next door is kind."],
      ],
      mistakes: [
        ["The person which called you is here.", "The person who called you is here.", "People take “who”."],
        ["The film which I saw it was boring.", "The film which I saw was boring.", "“Which” already means “it”."],
        ["I have a friend who his father is a pilot.", "I have a friend whose father is a pilot.", "For belonging, use “whose”."],
        ["This is the laptop who I use.", "This is the laptop that I use.", "Things take “which” or “that”."],
      ],
      ex: [
        ["pick", "The doctor ___ treated me was very kind.", ["which", "who", "whose"], 1, "People: who."],
        ["pick", "This is the restaurant ___ serves the best dosa.", ["who", "which", "whose"], 1, "Things: which."],
        ["pick", "I met a woman ___ son studies with mine.", ["who", "whose", "which"], 1, "Belonging: whose."],
        ["pick", "The bag ___ you gave me is really useful.", ["that", "who", "whose"], 0, "Things: that or which."],
        ["spot", "The teacher which taught us maths has retired.", "which", "who", "People: who."],
        ["spot", "The house that we bought it is very old.", "it", "", "Don’t repeat “it” after “that”."],
        ["spot", "He is the boy who his bike was stolen.", "who his", "whose", "Belonging: whose bike."],
        ["type", "Do you know anyone ___ can fix a washing machine?", ["who", "that"], "People: who."],
        ["order", "The man who lives upstairs is a chef.", "who + clause inside the sentence"],
        ["say", "Join them with “who”: “I have a friend. She lives in London.”", ["I have a friend who lives in London"], "who replaces “she”."],
      ],
      talk: "Describe three people you know using who or whose: “I have a friend who…”, “My neighbour, whose son…”.",
    },
    {
      id: "some-any-much-many",
      title: "Some, any, much, many, few, little",
      goal: "Talk about amounts naturally",
      wm: "Indefinite Pronouns and Adjectives of Quantity",
      intro:
        "Use “some” in positive sentences and offers, “any” in negatives and most questions. “Many” and “few” go with things you can count; “much” and “little” with things you can’t. “A few” and “a little” mean “some”; “few” and “little” without “a” mean “almost none”.",
      rules: [
        ["some: positive and offers. any: negative and questions.", "I have some time. / I don’t have any time.", "Would you like some water? Do you have any questions?"],
        ["many / few + countable; much / little + uncountable.", "many people, a few friends", "much money, a little sugar"],
        ["“a lot of” works with both, and sounds natural in positive sentences.", "She has a lot of friends.", "We have a lot of work."],
        ["a few / a little = some. few / little = not enough.", "I have a few friends here. (good)", "I have few friends here. (sad)"],
      ],
      mistakes: [
        ["I don’t have some money.", "I don’t have any money.", "Negative sentences use “any”."],
        ["There are too much cars.", "There are too many cars.", "Cars can be counted: many."],
        ["Give me little water.", "Give me a little water.", "“a little” = some; “little” = almost none."],
        ["I have much work today.", "I have a lot of work today.", "In positive sentences, “a lot of” sounds more natural."],
      ],
      ex: [
        ["pick", "Do you have ___ questions?", ["some", "any", "much"], 1, "Questions usually take “any”."],
        ["pick", "How ___ people came?", ["much", "many", "lot"], 1, "People can be counted: many."],
        ["pick", "Can I have ___ milk in my tea?", ["a few", "a little", "many"], 1, "Milk is uncountable: a little."],
        ["pick", "There isn’t ___ time left.", ["many", "much", "few"], 1, "Time is uncountable: much."],
        ["pick", "I’ve made ___ friends in my new office.", ["a few", "a little", "much"], 0, "Friends are countable: a few."],
        ["spot", "We didn't get some rain this year.", "some", "any", "Negatives use “any”."],
        ["spot", "How much times have you been to Mumbai?", "much", "many", "Times can be counted: many."],
        ["spot", "There were less people than last year.", "less", "fewer", "With countable nouns, careful English uses “fewer”."],
        ["type", "Would you like ___ biscuits? (some / any)", ["some"], "Offers use “some”."],
        ["order", "I don't have any plans for Sunday.", "Negative + any."],
        ["say", "Correct this: “There are too much people here.”", ["There are too many people here"], "People are countable: too many."],
      ],
      talk: "Describe your kitchen or your office desk: what you have a lot of, what you have only a few of, and what you don’t have any of.",
    },
  ],
};
