export const unit = {
  n: 10,
  title: "Adverbs and prepositions",
  note: "Where words go, and the small words in, on, at, to",
  lessons: [
    {
      id: "adverbs",
      title: "Adverbs: how and how often",
      goal: "Put adverbs like always, only and well in the right place",
      wm: "The Adverb: Position",
      intro:
        "Adverbs tell us how, when, where or how often. Most “how” adverbs end in -ly (quickly, carefully), but “good” becomes “well”. Frequency adverbs (always, usually, often, never) go before the main verb but after “be”. And “only” should sit right next to the word it limits.",
      rules: [
        ["Frequency: before the main verb, after am/is/are.", "I always drink tea.", "She is never late."],
        ["good (adjective) → well (adverb).", "She is a good speaker. She speaks well.", "I’m doing well, thanks."],
        ["Put “only” next to what it limits.", "I only have 100 rupees. / I have only 100 rupees.", "Only Ravi knew the answer."],
        ["hard and fast have no -ly. “Hardly” means almost not.", "She works hard.", "I hardly slept. (I slept very little.)"],
      ],
      mistakes: [
        ["Always I go by bus.", "I always go by bus.", "Frequency adverbs go before the main verb."],
        ["He speaks English very good.", "He speaks English very well.", "How he speaks: well."],
        ["I am working hardly.", "I am working hard.", "“Hardly” means almost not."],
        ["She is late always.", "She is always late.", "After “be”: is always."],
        ["I will come there only.", "I will come there.", "Using “only” for emphasis like this is Indian English; just drop it."],
      ],
      ex: [
        ["pick", "My brother ___ calls me on Sundays.", ["usually", "usual", "is usually"], 0, "Before the main verb."],
        ["pick", "You did the job really ___.", ["good", "well", "goodly"], 1, "How: well."],
        ["pick", "He is ___ at home in the evening.", ["always", "always is", "alway"], 0, "After “is”: is always."],
        ["pick", "I ___ know him. We met once.", ["hard", "hardly", "hardily"], 1, "Almost not: hardly."],
        ["pick", "She drives very ___.", ["careful", "carefully", "care"], 1, "How: carefully."],
        ["spot", "Sometimes she is working from home.", "is working", "works", "Habits use the simple present."],
        ["spot", "You did very good in the interview.", "good", "well", "How you did: well."],
        ["spot", "We go often to that café.", "go often", "often go", "Frequency adverb before the verb."],
        ["type", "I ___ eat meat. I’m vegetarian. (always / never)", ["never"], "never + verb"],
        ["order", "She has never been late for work.", "has + never + been"],
        ["say", "Correct this: “Always I am forgetting my keys.”", ["I always forget my keys", "I am always forgetting my keys", "I'm always forgetting my keys"], "I always forget my keys."],
      ],
      talk: "Talk about your habits: what you always, usually, sometimes and never do, and one thing you do really well.",
    },
    {
      id: "in-on-at-time",
      title: "In, on, at for time",
      goal: "Choose in, on or at for times, days and years",
      wm: "The Preposition: Time",
      intro:
        "A simple picture helps: “at” for exact points (at 5 pm, at night), “on” for days and dates (on Monday, on 15 August), and “in” for longer periods (in May, in 2020, in the morning). Some words take no preposition at all: this, next, last, every, tomorrow, yesterday.",
      rules: [
        ["at + clock time, night, the weekend (British), festivals as a period.", "at 7:30, at night", "at lunch, at the moment"],
        ["on + days and dates.", "on Friday, on my birthday", "on 26 January, on Diwali (the day)"],
        ["in + months, years, seasons, parts of the day.", "in July, in 1998, in summer", "in the morning, in the evening"],
        ["No preposition with this, next, last, every, today, tomorrow, yesterday.", "See you next week.", "I met him last Monday."],
      ],
      mistakes: [
        ["I was born on 1995.", "I was born in 1995.", "Years take “in”."],
        ["See you on next Monday.", "See you next Monday.", "No preposition before next / last / this."],
        ["The meeting is in 3 pm.", "The meeting is at 3 pm.", "Clock times take “at”."],
        ["I will call you in the night.", "I will call you at night.", "Say “at night” but “in the morning”."],
      ],
      ex: [
        ["pick", "The class starts ___ 9 o’clock.", ["in", "on", "at"], 2, "Clock time: at."],
        ["pick", "My birthday is ___ March.", ["in", "on", "at"], 0, "Months: in."],
        ["pick", "We’re meeting ___ Saturday.", ["in", "on", "at"], 1, "Days: on."],
        ["pick", "I usually read ___ night.", ["in", "on", "at"], 2, "at night"],
        ["pick", "What are you doing ___ weekend?", ["on this", "this", "in this"], 1, "No preposition before this."],
        ["spot", "She joined the company on 2021.", "on", "in", "Years: in."],
        ["spot", "I'll see you on next Friday.", "on next", "next", "No preposition before next."],
        ["spot", "My flight is at Monday morning.", "at", "on", "A specific day: on Monday morning."],
        ["type", "India became independent ___ 15 August 1947.", ["on"], "Dates: on."],
        ["order", "I get up at six in the morning.", "at + clock time, in the morning"],
        ["say", "Correct this: “I was born on 1998 in May.”", ["I was born in May 1998"], "in May 1998"],
      ],
      talk: "Tell the coach about important dates in your life: when you were born, when you started work or college, and your plans for next month.",
    },
    {
      id: "place-movement",
      title: "In, at, on, to, into: places",
      goal: "Say where you are and where you go without “reach to”",
      wm: "The Preposition: Place and Direction",
      intro:
        "For position: “in” an enclosed space (in the room, in Delhi), “at” a point or event (at the door, at a party), “on” a surface (on the table, on the bus). For movement: “to” a place, “into” inside something. Some verbs don’t take “to” at all: reach, enter, visit, call, attend.",
      rules: [
        ["in a room, city, country; at a point, address or event; on a surface, floor, or public transport.", "She’s in the kitchen.", "I’m at the station. He’s on the train."],
        ["go / come / travel to a place. But: go home, go there, go abroad.", "I went to Bangalore.", "Let’s go home."],
        ["No preposition after reach, enter, visit, attend, call, marry.", "We reached Delhi at night.", "She entered the room."],
      ],
      mistakes: [
        ["We reached to the hotel late.", "We reached the hotel late.", "reach + place, no “to”."],
        ["He entered into the room.", "He entered the room.", "enter + place, no “into”."],
        ["I am in the bus.", "I am on the bus.", "Buses, trains and planes: on."],
        ["I’ll go to there tomorrow.", "I’ll go there tomorrow.", "No “to” before there / home."],
        ["I am at Mumbai now.", "I am in Mumbai now.", "Cities: in."],
      ],
      ex: [
        ["pick", "Wait for me ___ the bus stop.", ["in", "at", "on"], 1, "A point: at."],
        ["pick", "My keys are ___ the table.", ["in", "at", "on"], 2, "A surface: on."],
        ["pick", "When did you reach ___?", ["to home", "home", "at home"], 1, "reach home"],
        ["pick", "I’ll meet you ___ the airport.", ["at", "in", "to"], 0, "A point: at."],
        ["pick", "She lives ___ the third floor.", ["in", "at", "on"], 2, "Floors: on."],
        ["spot", "We will reach to Pune by evening.", "reach to", "reach", "reach + place"],
        ["spot", "She is waiting in the train.", "in", "on", "Trains: on."],
        ["spot", "He attended to the conference.", "attended to", "attended", "attend + event"],
        ["type", "Put the milk back ___ the fridge.", ["in", "into"], "inside: in / into"],
        ["order", "I'll call you when I reach the office.", "reach + place, no “to”"],
        ["say", "Correct this: “I reached to office at nine.”", ["I reached the office at nine", "I reached office at nine", "I got to the office at nine", "I got to office at nine"], "reach the office, or get to the office."],
      ],
      talk: "Describe your journey to work or college: where you start, how you travel (on the bus? in a car?), where you change, and when you reach.",
    },
    {
      id: "verb-prepositions",
      title: "Discuss, explain, depend on",
      goal: "Use the right preposition after common verbs, or none at all",
      wm: "Correct Usage: Prepositions after Verbs",
      intro:
        "Many verbs come with a fixed preposition: depend on, listen to, wait for, married to. Others take none, though we often add one from habit: discuss (not discuss about), explain something to someone (not explain me), return (not return back). These patterns make a big difference to how natural you sound.",
      rules: [
        ["Fixed pairs: depend on, listen to, wait for, look for, belong to, agree with, married to, good at, afraid of, interested in.", "It depends on the weather.", "She’s married to a doctor."],
        ["No preposition: discuss, reach, attend, answer, marry, request, emphasize.", "Let’s discuss the budget.", "Please answer the question."],
        ["explain / describe / say something TO someone.", "Can you explain it to me?", "He said to me that…"],
        ["No “back” after return, revert, reply.", "She returned from Delhi.", "I’ll reply tomorrow."],
      ],
      mistakes: [
        ["Can you explain me this?", "Can you explain this to me?", "explain something to someone"],
        ["We discussed about the problem.", "We discussed the problem.", "discuss + thing"],
        ["He is married with my cousin.", "He is married to my cousin.", "married to"],
        ["It depends upon on you.", "It depends on you.", "depends on"],
        ["Please return back the book.", "Please return the book.", "“Return” already means “give back”."],
      ],
      ex: [
        ["pick", "Could you ___ how this works?", ["explain me", "explain to me", "explain"], 1, "explain to me"],
        ["pick", "We need to ___ the plan.", ["discuss", "discuss about", "discuss on"], 0, "discuss + thing"],
        ["pick", "Are you good ___ maths?", ["in", "at", "on"], 1, "good at"],
        ["pick", "I’ve been waiting ___ you for an hour!", ["for", "to", "—"], 0, "wait for"],
        ["pick", "She is afraid ___ dogs.", ["from", "of", "with"], 1, "afraid of"],
        ["spot", "Let's discuss about this tomorrow.", "discuss about", "discuss", "No “about”."],
        ["spot", "Please explain me the process.", "explain me the process", "explain the process to me", "explain something to someone"],
        ["spot", "My sister is married with an engineer.", "with", "to", "married to"],
        ["type", "Are you listening ___ me?", ["to"], "listen to"],
        ["order", "Can you describe the problem to me?", "describe + thing + to + person"],
        ["say", "Correct this: “Can you explain me the meaning?”", ["Can you explain the meaning to me"], "explain the meaning to me"],
      ],
      talk: "Talk about a problem at work or home: what you discussed, who explained things to you, what it depends on, and who you’re waiting for.",
    },
    {
      id: "conjunctions",
      title: "Joining ideas: and, but, although, unless",
      goal: "Connect ideas with the right joining word, used once",
      wm: "The Conjunction",
      intro:
        "Joining words (conjunctions) link ideas. And adds, but contrasts, so gives a result, because gives a reason. Although and though show contrast in one clause, unless means “if not”, and until means “up to the time when”. Use only one joining word between two clauses.",
      rules: [
        ["and (add), but (contrast), so (result), because (reason), or (choice).", "It was late, so we took a taxi.", "I stayed because I was tired."],
        ["although / though / even though: contrast. Never add “but”.", "Although it was expensive, I bought it.", "I went out even though it was raining."],
        ["unless = if not. until = up to the time.", "You won’t pass unless you study.", "Wait until I come back."],
        ["both … and, either … or, neither … nor, not only … but also.", "She speaks both Hindi and Tamil.", "Either call me or text me."],
      ],
      mistakes: [
        ["Although he tried, but he failed.", "Although he tried, he failed.", "Use only one joining word."],
        ["Unless you don’t hurry, you’ll miss it.", "Unless you hurry, you’ll miss it.", "“Unless” already means “if not”."],
        ["Both my brother as well as my sister are doctors.", "Both my brother and my sister are doctors.", "both … and"],
        ["Not only he sings but dances.", "He not only sings but also dances.", "not only … but also"],
      ],
      ex: [
        ["pick", "___ it was raining, the match continued.", ["Although", "But", "Because"], 0, "Contrast in one clause: although."],
        ["pick", "You can’t come in ___ you have a ticket.", ["unless", "if", "until"], 0, "unless = if not"],
        ["pick", "Stay here ___ the doctor arrives.", ["unless", "until", "although"], 1, "until = up to that time"],
        ["pick", "He is ___ smart and hard-working.", ["both", "either", "neither"], 0, "both … and"],
        ["pick", "I was hungry, ___ I made some noodles.", ["because", "so", "but"], 1, "Result: so."],
        ["spot", "Though she is young, but she is very wise.", "but", "", "One joining word only."],
        ["spot", "Unless you don't reply, I will call.", "don't reply", "reply", "“Unless” already means “if not”."],
        ["spot", "Neither my father or my mother drives.", "or", "nor", "neither … nor"],
        ["type", "I’ll take either tea ___ coffee, whatever is ready.", ["or"], "either … or"],
        ["order", "I went to work even though I was sick.", "even though + contrast"],
        ["say", "Join with “although”: “It was expensive. I bought it.”", ["Although it was expensive I bought it", "I bought it although it was expensive"], "Although it was expensive, I bought it."],
      ],
      talk: "Talk about a difficult decision you made. Use although, because, so, unless, and until to explain your thinking.",
    },
  ],
};
