export const unit = {
  n: 8,
  title: "Can, must, should, would",
  note: "Ability, rules, advice, and sounding polite",
  lessons: [
    {
      id: "can-could",
      title: "Can, could, be able to",
      goal: "Talk about ability and possibility, now and in the past",
      wm: "Auxiliary and Modal Verbs: Can, Could",
      intro:
        "Modal verbs like can and could are followed by the base form of a verb, with no “to” and no -s: “She can drive.” Use “can” for ability now, “could” for general ability in the past, and “be able to” for the tenses that can’t use “can” (will be able to, have been able to).",
      rules: [
        ["can / can’t + base form: ability now.", "I can speak three languages.", "He can’t come today."],
        ["could / couldn’t: ability in the past.", "I could swim when I was five.", "We couldn’t find a taxi."],
        ["be able to for other tenses.", "I’ll be able to help you tomorrow.", "I haven’t been able to sleep."],
      ],
      mistakes: [
        ["She can speaks English.", "She can speak English.", "After can: base form."],
        ["I can able to do it.", "I can do it. / I am able to do it.", "Use can OR be able to, not both."],
        ["I will can come.", "I will be able to come.", "Two modals can’t go together."],
        ["He can to drive.", "He can drive.", "No “to” after can."],
      ],
      ex: [
        ["pick", "My daughter can ___ really fast.", ["runs", "run", "to run"], 1, "can + base form"],
        ["pick", "I ___ ride a bike when I was six.", ["can", "could", "was can"], 1, "Past ability: could."],
        ["pick", "Will you ___ join the call later?", ["can", "be able to", "could"], 1, "will + be able to"],
        ["pick", "Sorry, I ___ hear you. The line is bad.", ["can’t", "don’t can", "not can"], 0, "Negative: can’t."],
        ["spot", "He can plays the flute.", "plays", "play", "can + base form"],
        ["spot", "I am not able to can open this file.", "able to can", "able to", "Use one: I’m not able to open / I can’t open."],
        ["spot", "We will can finish it by Friday.", "will can", "will be able to", "will + be able to"],
        ["type", "When I was young, I ___ eat anything without getting fat.", ["could"], "Past ability: could."],
        ["order", "I haven't been able to call him.", "have + been able to"],
        ["say", "Correct this: “She can able to cook very well.”", ["She can cook very well", "She is able to cook very well"], "Use can OR be able to."],
      ],
      talk: "Talk about three things you can do well, two things you couldn’t do as a child but can now, and one thing you hope you’ll be able to do next year.",
    },
    {
      id: "must-have-to",
      title: "Must, have to, don’t have to",
      goal: "Talk about rules and what isn’t necessary",
      wm: "Modal Verbs: Must, Have to",
      intro:
        "“Must” and “have to” both mean something is necessary. “Must” often shows the speaker’s own feeling (“I must call Mom”), “have to” an outside rule (“I have to wear a uniform”). But in the negative they are very different: “mustn’t” means don’t do it, while “don’t have to” means it isn’t necessary.",
      rules: [
        ["must / have to + base form: it’s necessary.", "You must try this.", "I have to be at work by nine."],
        ["mustn’t = it’s not allowed.", "You mustn’t smoke here.", "We mustn’t be late."],
        ["don’t have to = it’s not necessary (you can if you want).", "You don’t have to come.", "She doesn’t have to work on Saturdays."],
        ["Past: had to (there is no “musted”).", "I had to wait for an hour.", "Did you have to pay?"],
      ],
      mistakes: [
        ["You must have to come.", "You must come. / You have to come.", "Use one: must OR have to."],
        ["You mustn’t bring anything, we have food.", "You don’t have to bring anything.", "Not necessary = don’t have to."],
        ["Yesterday I must go to the bank.", "Yesterday I had to go to the bank.", "Past: had to."],
        ["She have to leave early.", "She has to leave early.", "she → has to"],
      ],
      ex: [
        ["pick", "You ___ wear a seatbelt. It’s the law.", ["must", "don’t have to", "mustn’t"], 0, "Necessary: must."],
        ["pick", "It’s a holiday tomorrow, so I ___ get up early.", ["mustn’t", "don’t have to", "must"], 1, "Not necessary: don’t have to."],
        ["pick", "You ___ tell anyone. It’s a secret.", ["mustn’t", "don’t have to", "must"], 0, "Not allowed: mustn’t."],
        ["pick", "Last night we ___ take a taxi home.", ["must", "had to", "have to"], 1, "Past: had to."],
        ["pick", "My brother ___ travel a lot for work.", ["have to", "has to", "must to"], 1, "he → has to"],
        ["spot", "We must have to submit it today.", "must have to", "have to", "Use one: have to."],
        ["spot", "Last week I must work on Sunday.", "must", "had to", "Past: had to."],
        ["spot", "You mustn't pay now, you can pay later.", "mustn't", "don't have to", "Not necessary: don’t have to."],
        ["type", "Does she ___ to wear a uniform?", ["have"], "does + have to"],
        ["order", "You don't have to reply today.", "Not necessary: don’t have to."],
        ["say", "Correct this: “We must have to finish this by Monday.”", ["We must finish this by Monday", "We have to finish this by Monday"], "Use one: must OR have to."],
      ],
      talk: "Describe the rules at your office, college or home: what you have to do, what you mustn’t do, and what you don’t have to do.",
    },
    {
      id: "should",
      title: "Should, ought to, had better",
      goal: "Give advice without sounding too strong",
      wm: "Modal Verbs: Should, Ought",
      intro:
        "Use “should” to give or ask for advice: “You should see a doctor.” “Ought to” means the same but sounds more formal. “Had better” is stronger: there is a warning in it. For softer advice, add “I think” or “maybe”.",
      rules: [
        ["should / shouldn’t + base form.", "You should rest.", "We shouldn’t spend so much."],
        ["Ask for advice: Should I…?", "Should I call him?", "What should I wear?"],
        ["had better (’d better) + base form: a warning.", "You’d better leave now or you’ll miss the train.", "We’d better not be late."],
        ["Soften it: I think you should… / Maybe you could…", "I think you should talk to her.", "Maybe you could try again tomorrow."],
      ],
      mistakes: [
        ["You should to see a doctor.", "You should see a doctor.", "No “to” after should."],
        ["You had better to go.", "You had better go.", "No “to” after had better."],
        ["I think you shouldn’t worry.", "I don’t think you should worry.", "More natural: “I don’t think you should…”."],
        ["What I should do?", "What should I do?", "Question order: should before I."],
      ],
      ex: [
        ["pick", "You look tired. You ___ go to bed.", ["should", "should to", "must to"], 0, "Advice: should + base form."],
        ["pick", "___ I bring anything to the party?", ["Should", "Must", "Had"], 0, "Asking for advice: Should I…?"],
        ["pick", "It’s going to rain. We ___ take an umbrella.", ["had better", "had better to", "better to"], 0, "had better + base form"],
        ["pick", "You ___ eat so much sugar.", ["shouldn’t", "don’t should", "should not to"], 0, "shouldn’t + base form"],
        ["spot", "You should to apply for this job.", "should to", "should", "No “to” after should."],
        ["spot", "What I should say to him?", "What I should", "What should I", "Question order."],
        ["spot", "We had better to hurry.", "better to", "better", "No “to” after had better."],
        ["type", "I ___ think you should buy it. It’s too expensive.", ["don't", "don’t", "do not"], "I don’t think you should…"],
        ["order", "Maybe you should talk to your manager.", "Soft advice: maybe you should…"],
        ["say", "Give advice with “should”: your friend has a headache.", ["You should*", "I think you should*", "Maybe you should*"], "You should + base form, e.g. You should take a rest."],
      ],
      talk: "A friend wants to improve their English quickly. Give them five pieces of advice using should, shouldn’t, and had better.",
    },
    {
      id: "polite-requests",
      title: "Would, could: sounding polite",
      goal: "Ask for things politely and naturally",
      wm: "Modal Verbs: Would, Could, May",
      intro:
        "How you ask matters as much as what you ask. “I want water” or “Give me the file” can sound rude in English even when you don’t mean it. Use could, would, may and “would like” to make requests and offers polite. “Kindly” and “do the needful” sound old-fashioned; modern English prefers “Could you please…?”",
      rules: [
        ["Could you / Would you + base form …?", "Could you send me the link?", "Would you mind closing the window?"],
        ["Can I / Could I / May I …? to ask for something.", "Could I have some water, please?", "May I come in?"],
        ["would like = a polite want.", "I’d like a coffee, please.", "Would you like some tea?"],
        ["Would you mind + -ing?", "Would you mind waiting a minute?", "Would you mind if I sat here?"],
      ],
      mistakes: [
        ["I want one coffee.", "Could I have a coffee, please?", "“I want” sounds demanding in a shop."],
        ["Kindly do the needful.", "Could you please take care of this?", "Say clearly what you need."],
        ["Would you mind to wait?", "Would you mind waiting?", "Would you mind + -ing."],
        ["Can you please revert back?", "Could you please reply?", "“Revert back” isn’t used this way outside India. Say “reply” or “get back to me”."],
      ],
      ex: [
        ["pick", "___ you help me with this bag, please?", ["Could", "Should", "Must"], 0, "Polite request: Could you…?"],
        ["pick", "I’d ___ a table for two, please.", ["like", "want", "liking"], 0, "I’d like…"],
        ["pick", "Would you mind ___ the music down?", ["to turn", "turning", "turn"], 1, "Would you mind + -ing"],
        ["pick", "___ I use your phone for a minute?", ["May", "Would", "Should"], 0, "Asking permission: May I…?"],
        ["pick", "Could you ___ me by tomorrow?", ["revert back", "get back to", "revert back to"], 1, "Natural: get back to me."],
        ["spot", "Would you mind to send me the file?", "to send", "sending", "Would you mind + -ing"],
        ["spot", "I want one masala dosa.", "I want", "Could I have", "Polite: Could I have…?"],
        ["spot", "Please revert back by Friday.", "revert back", "reply", "Say reply / get back to me."],
        ["type", "___ you like something to drink?", ["Would"], "Offer: Would you like…?"],
        ["order", "Could you please call me back later?", "Could you please + base form"],
        ["say", "Ask politely for the bill in a restaurant.", ["Could I have the bill please", "Could we have the bill please", "Can I have the bill please", "Can we have the bill please", "Could we get the bill please", "Could I get the bill please", "May I have the bill please"], "Could I have the bill, please?"],
      ],
      talk: "You are at a hotel. Politely ask for three things (a late checkout, a taxi, extra towels) and offer to help another guest.",
    },
    {
      id: "should-have",
      title: "Should have, could have, must have",
      goal: "Talk about past regrets and guesses",
      wm: "Modal Verbs: Perfect Forms",
      intro:
        "Modal + have + past participle talks about the past. “Should have” is a regret or criticism: it didn’t happen, but it was a good idea. “Could have” is a possibility that didn’t happen. “Must have” is a strong guess about the past. In speech they sound like “shoulda”, “coulda”, “musta”.",
      rules: [
        ["should have done = it was a good idea, but it didn’t happen.", "I should have left earlier.", "You shouldn’t have said that."],
        ["could have done = it was possible, but it didn’t happen.", "You could have called me!", "We could have won."],
        ["must have done = I’m almost sure it happened.", "She must have forgotten.", "They must have been tired."],
      ],
      mistakes: [
        ["I should have went.", "I should have gone.", "have + past participle"],
        ["You should had told me.", "You should have told me.", "Always “have” after a modal."],
        ["He must be left already.", "He must have left already.", "Past guess: must have + past participle."],
        ["I should of called.", "I should have called.", "“Should’ve” sounds like “should of”, but the word is “have”."],
      ],
      ex: [
        ["pick", "I failed. I ___ harder.", ["should study", "should have studied", "must have studied"], 1, "Regret: should have studied."],
        ["pick", "The ground is wet. It ___ at night.", ["must have rained", "should have rained", "must rain"], 0, "Strong guess about the past."],
        ["pick", "Why did you walk? You ___ a taxi.", ["could have taken", "could take", "must have taken"], 0, "A possibility you didn’t use."],
        ["pick", "You ___ shouted at him. He felt bad.", ["shouldn’t have", "mustn’t have", "couldn’t"], 0, "Criticism: shouldn’t have."],
        ["spot", "We should have took the earlier flight.", "took", "taken", "have + past participle"],
        ["spot", "She must have forget her phone.", "forget", "forgotten", "have + past participle"],
        ["spot", "You should had asked me first.", "had", "have", "modal + have"],
        ["type", "He isn’t answering. He ___ have gone to sleep.", ["must"], "Strong guess: must have."],
        ["order", "I should have saved more money.", "should + have + past participle"],
        ["say", "Say a regret with “should have”: you didn’t bring an umbrella and got wet.", ["I should have brought an umbrella", "I should have taken an umbrella", "I should have carried an umbrella"], "I should have brought an umbrella."],
      ],
      talk: "Talk about a decision you regret and what you should have done instead, and something you could have done but didn’t.",
    },
  ],
};
