export const unit = {
  n: 2,
  title: "Nouns and articles",
  note: "a, an, the, plurals, and words you can’t count",
  lessons: [
    {
      id: "countable-uncountable",
      title: "Things you can and can’t count",
      goal: "Stop saying “advices”, “informations” and “furnitures”",
      wm: "Nouns: Kinds of Nouns",
      intro:
        "Some nouns can be counted: one chair, two chairs. Others can’t: you can’t say “two waters” or “an advice”. Uncountable nouns have no plural and never take “a” or “an”. Many of the most common Indian-English mistakes come from these words.",
      rules: [
        ["Countable nouns have a plural and can take a/an.", "a suggestion, two suggestions", "an idea, many ideas"],
        ["Uncountable nouns have no plural and no a/an. Use “some”, “a lot of”, or “a piece of”.", "Can I give you some advice?", "She gave me a useful piece of information."],
        ["These are always uncountable: advice, information, furniture, luggage, baggage, equipment, news, homework, work, research, feedback, knowledge, traffic, weather.", "The news is good.", "We got a lot of feedback."],
      ],
      mistakes: [
        ["He gave me many advices.", "He gave me a lot of advice.", "“Advice” has no plural."],
        ["I need an information.", "I need some information.", "“Information” is uncountable, so no “an” and no plural."],
        ["We bought new furnitures.", "We bought new furniture.", "“Furniture” has no plural."],
        ["The news are very bad.", "The news is very bad.", "“News” ends in -s but it is singular."],
        ["Please give your feedbacks.", "Please give your feedback.", "“Feedback” has no plural."],
      ],
      ex: [
        ["pick", "Can you give me some ___?", ["advice", "advices", "an advice"], 0, "“Advice” is uncountable."],
        ["pick", "How much ___ do you have?", ["luggages", "luggage", "a luggage"], 1, "“Luggage” is uncountable."],
        ["pick", "The news ___ really surprising.", ["are", "were", "was"], 2, "“News” is singular: the news was."],
        ["pick", "I have a lot of ___ to finish tonight.", ["works", "work", "a work"], 1, "“Work” (the job you do) is uncountable."],
        ["pick", "She has three ___ for the project.", ["idea", "ideas", "ideaes"], 1, "“Idea” is countable: three ideas."],
        ["spot", "Thank you for all the informations.", "informations", "information", "“Information” has no plural."],
        ["spot", "We need to buy some new equipments.", "equipments", "equipment", "“Equipment” has no plural."],
        ["spot", "There were too many traffics this morning.", "many traffics", "much traffic", "“Traffic” is uncountable: much traffic."],
        ["type", "Let me give you a piece of ___: sleep early.", ["advice"], "a piece of advice"],
        ["order", "Thanks for your helpful feedback.", "“Feedback” stays singular."],
        ["say", "Correct this: “My teacher gave me many good advices.”", ["My teacher gave me a lot of good advice", "My teacher gave me lots of good advice", "My teacher gave me some good advice", "My teacher gave me much good advice"], "“Advice” has no plural: a lot of good advice."],
      ],
      talk: "Talk about the best advice someone gave you and the news you heard this week. Be careful with “advice”, “news” and “information”.",
    },
    {
      id: "plurals",
      title: "Plurals that break the rules",
      goal: "Use the right plural, and know which words are always plural",
      wm: "Nouns: Number",
      intro:
        "Most plurals just add -s. But some nouns change completely (child → children), some are always plural (trousers, scissors), and some look plural but aren’t (news, mathematics). Numbers used as adjectives never take -s: a five-star hotel.",
      rules: [
        ["Irregular plurals change the word.", "one child, two children", "a man, two men; a person, many people"],
        ["Pairs are always plural: trousers, jeans, scissors, glasses, pants.", "My jeans are torn.", "Where are the scissors?"],
        ["A number joined to a noun before another noun stays singular.", "a ten-minute break", "a five-year-old boy"],
        ["After “one of”, use a plural noun.", "one of my friends", "one of the best books"],
      ],
      mistakes: [
        ["One of my friend is a doctor.", "One of my friends is a doctor.", "After “one of” the noun is plural."],
        ["I bought a new jeans.", "I bought new jeans. / I bought a new pair of jeans.", "“Jeans” is plural, so no “a”."],
        ["It was a ten-minutes walk.", "It was a ten-minute walk.", "Before a noun, the number phrase stays singular."],
        ["Many peoples came to the party.", "Many people came to the party.", "“People” is already plural."],
        ["My childrens go to school.", "My children go to school.", "“Children” is already plural."],
      ],
      ex: [
        ["pick", "My ___ are too tight.", ["trouser", "trousers", "trouseres"], 1, "Trousers are always plural."],
        ["pick", "She is one of my closest ___.", ["friend", "friends", "friend's"], 1, "one of + plural"],
        ["pick", "We stayed in a ___ hotel.", ["five-stars", "five-star", "five star's"], 1, "Before a noun, the number phrase stays singular."],
        ["pick", "How many ___ work in your office?", ["peoples", "person", "people"], 2, "The plural of “person” is usually “people”."],
        ["pick", "Where ___ my glasses?", ["is", "are", "was"], 1, "Glasses are plural."],
        ["spot", "He has two childs.", "childs", "children", "The plural of child is children."],
        ["spot", "We took a two-hours flight to Goa.", "two-hours", "two-hour", "Before a noun: a two-hour flight."],
        ["spot", "One of the student was absent.", "student", "students", "one of + plural"],
        ["type", "I need a new pair of ___. (jeans / jean)", ["jeans"], "a pair of jeans"],
        ["order", "It is one of the best films I have seen.", "one of + the best + plural noun"],
        ["say", "Correct this: “She has three childrens.”", ["She has three children"], "“Children” is already plural."],
      ],
      talk: "Describe your family and the people in your office or class. Use “one of…”, and plurals like children, people, and women.",
    },
    {
      id: "possessive",
      title: "My friend’s house",
      goal: "Show who owns something with ’s",
      wm: "Nouns: Case",
      intro:
        "To show that something belongs to someone, English adds ’s to the owner: my brother’s car. For things (not people), we usually use “of”: the end of the film. Leaving out the ’s (“my friend house”) is a very common mistake.",
      rules: [
        ["Person + ’s + thing.", "my sister’s phone", "Rahul’s birthday"],
        ["Plural owner ending in -s: add only ’.", "my parents’ house", "the students’ results"],
        ["For things and places, “of” is more natural.", "the top of the page", "the name of the street"],
        ["Time can take ’s too.", "today’s meeting", "a week’s holiday"],
      ],
      mistakes: [
        ["I went to my friend house.", "I went to my friend’s house.", "Add ’s to show it belongs to your friend."],
        ["This is my father car.", "This is my father’s car.", "Add ’s: my father’s car."],
        ["The table’s leg is broken.", "The leg of the table is broken.", "For things, “of” sounds more natural."],
        ["Yesterday meeting was long.", "Yesterday’s meeting was long.", "Time words take ’s: yesterday’s meeting."],
      ],
      ex: [
        ["pick", "I stayed at my ___ place.", ["cousin", "cousin’s", "cousins"], 1, "cousin’s place = the place of my cousin"],
        ["pick", "My ___ house is in Jaipur.", ["parents’", "parent’s", "parents"], 0, "Two parents: parents’ house."],
        ["pick", "Did you see ___ news?", ["today", "today’s", "todays"], 1, "today’s news"],
        ["pick", "Write your name at the top ___.", ["of the page", "page’s", "the page"], 0, "For things: the top of the page."],
        ["spot", "Is this your brother bike?", "brother", "brother’s", "Add ’s: your brother’s bike."],
        ["spot", "We are going to my uncle wedding.", "uncle", "uncle’s", "Add ’s: my uncle’s wedding."],
        ["spot", "Last week class was cancelled.", "Last week", "Last week’s", "Time words take ’s."],
        ["type", "This is Priya___ laptop, not mine.", ["’s", "'s"], "Priya’s laptop"],
        ["order", "My sister’s husband works in a bank.", "owner + ’s + thing"],
        ["say", "Say it with ’s: “the car of my father”.", ["my father's car", "My father’s car"], "my father’s car"],
      ],
      talk: "Describe your best friend’s home or your family members’ jobs. Use ’s at least four times: my mother’s…, my friend’s….",
    },
    {
      id: "a-an",
      title: "A or an",
      goal: "Choose a/an by sound, not by spelling",
      wm: "The Articles",
      intro:
        "Use “a” before a consonant sound and “an” before a vowel sound. What matters is the sound, not the letter. “Hour” starts with a vowel sound (the h is silent), so it’s “an hour”. “University” starts with a “yoo” sound, so it’s “a university”.",
      rules: [
        ["“an” before a vowel sound.", "an apple, an hour, an honest man", "an MBA (em-bee-ay), an SUV (es-yoo-vee)"],
        ["“a” before a consonant sound, including a “yoo” or “w” sound.", "a university, a European city", "a one-way street (one = “wun”)"],
        ["Use a/an for one person or thing, and for someone’s job.", "She is a doctor.", "I have an idea."],
      ],
      mistakes: [
        ["He is engineer.", "He is an engineer.", "A job needs a/an."],
        ["It will take a hour.", "It will take an hour.", "The h in “hour” is silent, so it starts with a vowel sound."],
        ["She studies at an university.", "She studies at a university.", "“University” starts with a “yoo” sound."],
        ["I did a MBA.", "I did an MBA.", "MBA starts with the sound “em”."],
      ],
      ex: [
        ["pick", "I waited for ___ hour.", ["a", "an", "the"], 1, "Silent h: an hour."],
        ["pick", "She works for ___ European company.", ["a", "an"], 0, "“European” starts with a “yoo” sound."],
        ["pick", "My brother is ___ architect.", ["a", "an", "—"], 1, "Jobs take a/an; “architect” starts with a vowel sound."],
        ["pick", "It was ___ honest mistake.", ["a", "an"], 1, "Silent h: an honest mistake."],
        ["pick", "He has ___ unique style.", ["a", "an"], 0, "“Unique” starts with “yoo”."],
        ["pick", "She has ___ MA in English.", ["a", "an"], 1, "MA starts with the sound “em”."],
        ["spot", "My father is lawyer.", "lawyer", "a lawyer", "A job needs “a”."],
        ["spot", "This is an one-time offer.", "an", "a", "“One” starts with a “w” sound."],
        ["spot", "We stayed in an hotel near the beach.", "an", "a", "In modern English the h in “hotel” is said, so it’s “a hotel”."],
        ["type", "Is there ___ ATM near here?", ["an"], "ATM starts with the sound “ay”."],
        ["say", "Correct this: “She is doctor and her husband is engineer.”", ["She is a doctor and her husband is an engineer", "She's a doctor and her husband's an engineer", "She's a doctor and her husband is an engineer"], "Jobs need a/an: a doctor, an engineer."],
      ],
      talk: "Introduce yourself and three people in your family: their jobs and one thing about each. Use a or an before every job.",
    },
    {
      id: "the",
      title: "When to say “the”",
      goal: "Use “the” when both people know exactly which one",
      wm: "The Articles",
      intro:
        "Use “the” when the listener knows exactly which thing you mean: because you mentioned it before, because there is only one, or because the rest of the sentence makes it clear. Use “a” for something mentioned for the first time.",
      rules: [
        ["First mention: a. Second mention: the.", "I bought a phone. The phone is great.", "We saw a movie. The movie was long."],
        ["Only one of it exists, or it’s clear which one.", "the sun, the moon, the internet", "Close the door, please."],
        ["Superlatives, “same”, and ordinal numbers take “the”.", "the best day, the same shirt", "the first time, the last bus"],
        ["Instruments, rivers, seas and some countries take “the”.", "She plays the guitar.", "the Ganga, the USA, the UK"],
      ],
      mistakes: [
        ["He is best player in the team.", "He is the best player in the team.", "Superlatives need “the”."],
        ["We wear same uniform.", "We wear the same uniform.", "Say “the same”."],
        ["I play guitar every evening.", "I play the guitar every evening.", "British and Indian English use “the” with instruments."],
        ["This is first time I’m here.", "This is the first time I’m here.", "first, second, last → the first time"],
      ],
      ex: [
        ["pick", "She is ___ smartest person I know.", ["a", "the", "—"], 1, "Superlatives take “the”."],
        ["pick", "I saw ___ dog in the park. ___ dog was huge.", ["a / The", "the / A", "a / A"], 0, "First mention “a”, then “the”."],
        ["pick", "Can you switch off ___ fan?", ["a", "the", "—"], 1, "We both know which fan."],
        ["pick", "We live in ___ same building.", ["a", "the", "—"], 1, "Always “the same”."],
        ["pick", "This is ___ last train tonight.", ["a", "the", "—"], 1, "“last” takes “the”."],
        ["spot", "Mount Everest is highest mountain in the world.", "highest", "the highest", "Superlatives need “the”."],
        ["spot", "Did you finish reading book I gave you?", "book", "the book", "It’s a specific book, so “the”."],
        ["spot", "My son is learning piano.", "piano", "the piano", "Instruments take “the”."],
        ["type", "Is this ___ first time you are visiting Kerala?", ["the"], "the first time"],
        ["order", "This is the best tea in the city.", "the + superlative"],
        ["say", "Complete: “Delhi is ___ capital of India.”", ["Delhi is the capital of India"], "There is only one capital, so “the”."],
      ],
      talk: "Tell the coach about the best trip of your life: where you stayed, what you saw, and the first thing you did. Watch every “the”.",
    },
    {
      id: "no-article",
      title: "When not to use an article",
      goal: "Drop the article with general ideas, meals and places like home",
      wm: "The Articles: Omission",
      intro:
        "Sometimes English uses no article at all. Talking about things in general (“Dogs are loyal”), meals, most languages and subjects, and some fixed places like home, school, work and bed. Adding “the” here is a common mistake.",
      rules: [
        ["General plural or uncountable nouns: no article.", "I love books.", "Money isn’t everything."],
        ["Meals, languages, subjects, sports: no article.", "Let’s have lunch.", "She speaks Tamil. He plays cricket."],
        ["go to school / work / bed / church; go home; at home; by bus / car / train.", "I go to work by bus.", "She went home early."],
      ],
      mistakes: [
        ["I am going to the home.", "I am going home.", "“Home” takes no article and no “to”."],
        ["The life is beautiful.", "Life is beautiful.", "Life in general: no article."],
        ["He came by the train.", "He came by train.", "by + transport, no article."],
        ["I love the chocolate.", "I love chocolate.", "Chocolate in general: no article."],
        ["We had a lunch at one.", "We had lunch at one.", "Meals take no article."],
      ],
      ex: [
        ["pick", "I usually go to ___ at eleven.", ["the bed", "bed", "a bed"], 1, "go to bed"],
        ["pick", "___ is a great teacher.", ["The experience", "Experience", "An experience"], 1, "Experience in general: no article."],
        ["pick", "We went there ___ car.", ["by the", "by", "by a"], 1, "by car"],
        ["pick", "She reached ___ at nine.", ["to home", "home", "the home"], 1, "reach home"],
        ["pick", "Do you like ___?", ["the cricket", "cricket", "a cricket"], 1, "Sports take no article."],
        ["spot", "I don't eat the meat.", "the meat", "meat", "Meat in general: no article."],
        ["spot", "Let's have a dinner together.", "a dinner", "dinner", "Meals take no article."],
        ["spot", "My son goes to the school by the bus.", "the bus", "bus", "by bus"],
        ["type", "I work from ___ on Fridays.", ["home"], "work from home"],
        ["order", "I usually go to work by metro.", "No article with work and by + transport."],
        ["say", "Correct this: “I am going to the home now.”", ["I am going home now", "I'm going home now"], "go home: no “the”, no “to”."],
      ],
      talk: "Describe your normal weekday: when you have breakfast, how you go to work or college, and when you get home. Watch where you don’t need “the”.",
    },
  ],
};
