export const unit = {
  n: 11,
  title: "If, wish, and reported speech",
  note: "Real and imaginary situations, and telling what someone said",
  lessons: [
    {
      id: "if-real",
      title: "If it rains, we’ll stay in",
      goal: "Talk about real possibilities with if",
      wm: "Adverb Clauses of Condition",
      intro:
        "For facts that are always true, use present + present: “If you heat ice, it melts.” For real possibilities in the future, use if + present, then will: “If it rains, we’ll stay in.” Never put “will” in the if-half.",
      rules: [
        ["Always true: if + present, present.", "If I drink coffee late, I can’t sleep.", "If you press this, the light turns on."],
        ["Real future: if + present, will + verb.", "If you leave now, you’ll catch the train.", "If she calls, I’ll tell her."],
        ["The if-half can come first (with a comma) or second.", "I’ll help you if you ask.", "If you ask, I’ll help you."],
      ],
      mistakes: [
        ["If you will come, I will be happy.", "If you come, I’ll be happy.", "No “will” after if."],
        ["If it will rain, the match will stop.", "If it rains, the match will stop.", "No “will” after if."],
        ["If I will get time, I will call.", "If I get time, I’ll call.", "No “will” after if."],
        ["If you heat water, it will boils.", "If you heat water, it boils.", "A fact: present + present."],
      ],
      ex: [
        ["pick", "If you ___ now, you’ll be on time.", ["leave", "will leave", "left"], 0, "if + present"],
        ["pick", "If I see him, I ___ him your message.", ["give", "will give", "gave"], 1, "Real future: will give."],
        ["pick", "If you mix red and white, you ___ pink.", ["get", "will got", "got"], 0, "A fact: present."],
        ["pick", "We’ll go to the beach if the weather ___ good.", ["will be", "is", "was"], 1, "if + present"],
        ["spot", "If you will need help, call me.", "will need", "need", "No “will” after if."],
        ["spot", "If she will study, she will pass.", "will study", "studies", "if + present"],
        ["spot", "If I finish early, I come to your place.", "come", "will come", "Real future: will come."],
        ["type", "If it ___ (rain) tomorrow, we’ll cancel the trip.", ["rains"], "if + present"],
        ["order", "If you need anything, just call me.", "if + present, then an instruction"],
        ["say", "Correct this: “If I will get the job, I will buy a car.”", ["If I get the job I will buy a car", "If I get the job I'll buy a car"], "if + present, will + verb"],
      ],
      talk: "Talk about your plans for next month with “if”: If I get time…, If the weather is good…, If I save enough….",
    },
    {
      id: "if-imaginary",
      title: "If I were you",
      goal: "Talk about imaginary situations with if + past, would",
      wm: "Conditional Sentences",
      intro:
        "To talk about something unreal or unlikely now, use if + past, then would: “If I had more time, I would learn the piano.” The past form here doesn’t mean the past; it means “not real”. With be, careful English uses “were” for everyone: “If I were you…”.",
      rules: [
        ["Unreal now: if + past, would + verb.", "If I won the lottery, I would travel.", "If he lived closer, we’d meet more."],
        ["If I were you, I’d… is the classic way to give advice.", "If I were you, I’d take the job.", "If she were here, she’d know."],
        ["No “would” in the if-half.", "If I knew, I’d tell you.", "If we had a car, we’d drive."],
      ],
      mistakes: [
        ["If I would have money, I would buy it.", "If I had money, I would buy it.", "No “would” in the if-half."],
        ["If I am you, I will go.", "If I were you, I would go.", "Advice: If I were you, I’d…"],
        ["If I knew, I will tell you.", "If I knew, I would tell you.", "Past in the if-half → would."],
        ["If she was here, she would helped.", "If she were here, she would help.", "would + base form"],
      ],
      ex: [
        ["pick", "If I ___ rich, I’d buy a big house.", ["am", "were", "will be"], 1, "Unreal now: were."],
        ["pick", "If I were you, I ___ call her.", ["will", "would", "am"], 1, "Advice: I would."],
        ["pick", "If she ___ how to drive, she’d go alone.", ["knows", "knew", "would know"], 1, "if + past"],
        ["pick", "What would you do if you ___ a million dollars?", ["have", "had", "would have"], 1, "if + past"],
        ["spot", "If I would know his number, I would call him.", "would know", "knew", "No “would” in the if-half."],
        ["spot", "If I am you, I would apologize.", "am", "were", "If I were you…"],
        ["spot", "If we had a garden, we will grow vegetables.", "will", "would", "Unreal: would."],
        ["type", "If I ___ (be) taller, I would play basketball.", ["were", "was"], "If I were…"],
        ["order", "If I were you, I would talk to him.", "If I were you, I would…"],
        ["say", "Give advice starting with “If I were you”: your friend is always tired.", ["If I were you I would*", "If I were you I'd*"], "If I were you, I’d sleep earlier."],
      ],
      talk: "Answer these imaginary questions: If you could live anywhere, where would you live? If you had a free year, what would you do? If you were the prime minister, what would you change?",
    },
    {
      id: "if-past-wish",
      title: "If I had known, I wish",
      goal: "Talk about past regrets with if + had, and use “I wish” correctly",
      wm: "Conditional Sentences; Wishes",
      intro:
        "To imagine a different past, use if + had + past participle, then would have + past participle: “If I had known, I would have come.” “I wish” works the same way: wish + past for now (“I wish I had a car”), and wish + had done for the past (“I wish I had studied more”).",
      rules: [
        ["Different past: if + had done, would have done.", "If I had left earlier, I wouldn’t have missed the bus.", "If you had asked, I would have helped."],
        ["I wish + past = I want the present to be different.", "I wish I lived near the sea.", "I wish I could speak French."],
        ["I wish + had done = a regret about the past.", "I wish I had listened to you.", "She wishes she hadn’t said that."],
      ],
      mistakes: [
        ["If I would have known, I would have come.", "If I had known, I would have come.", "The if-half takes “had known”."],
        ["If you told me, I would have come.", "If you had told me, I would have come.", "Past regret: had told."],
        ["I wish I have a car.", "I wish I had a car.", "wish + past"],
        ["I wish I studied harder in school.", "I wish I had studied harder in school.", "A past regret: had studied."],
      ],
      ex: [
        ["pick", "If I ___ about the traffic, I would have left earlier.", ["knew", "had known", "would know"], 1, "if + had known"],
        ["pick", "If she had studied, she ___ passed.", ["would have", "would", "had"], 0, "would have + past participle"],
        ["pick", "I wish I ___ taller.", ["am", "were", "will be"], 1, "wish + past"],
        ["pick", "I wish I ___ that email. It was a mistake.", ["didn’t send", "hadn’t sent", "don’t send"], 1, "Past regret: hadn’t sent."],
        ["spot", "If I would have seen you, I would have said hi.", "would have seen", "had seen", "if + had seen"],
        ["spot", "I wish I can sing.", "can", "could", "wish + could"],
        ["spot", "If we had taken a taxi, we would reach on time.", "would reach", "would have reached", "would have + past participle"],
        ["type", "I wish I ___ (not / eat) so much. I feel sick.", ["hadn't eaten", "had not eaten", "hadn’t eaten"], "Past regret: hadn’t eaten."],
        ["order", "If you had called me, I would have helped.", "if + had done, would have done"],
        ["say", "Say a regret with “I wish”: you didn’t learn music as a child.", ["I wish I had learned music*", "I wish I had learnt music*", "I wish I had learned*", "I wish I had learnt*"], "I wish I had learned music as a child."],
      ],
      talk: "Talk about one thing you wish were different in your life now, and one decision from the past: what would have happened if you had chosen differently?",
    },
    {
      id: "reported-statements",
      title: "He said that…",
      goal: "Report what someone said, moving the tense back",
      wm: "Direct and Indirect Speech",
      intro:
        "When we report what someone said, the tense usually moves one step back: “I am tired” → She said she was tired. Pronouns and time words change too: “tomorrow” becomes “the next day”. Use “say” without a person, and “tell” with a person: He said that… / He told me that….",
      rules: [
        ["Tense moves back: am → was, will → would, can → could, went → had gone.", "“I’m busy.” → He said he was busy.", "“I’ll call.” → She said she would call."],
        ["say (something), tell (someone) something.", "She said that she was leaving.", "She told me that she was leaving."],
        ["If it’s still true, you can keep the tense.", "He said he lives in Pune.", "She said the shop opens at ten."],
      ],
      mistakes: [
        ["He said me that he was busy.", "He told me that he was busy.", "tell + person; say + no person."],
        ["She told that she will come.", "She said that she would come.", "say (no person), and will → would."],
        ["He said that he is coming tomorrow. (said last week)", "He said that he was coming the next day.", "Move the tense and the time back."],
        ["I told to him the truth.", "I told him the truth.", "tell + person, no “to”."],
      ],
      ex: [
        ["pick", "She ___ me she was tired.", ["said", "told", "told to"], 1, "tell + person"],
        ["pick", "He ___ that he would be late.", ["said", "told", "said me"], 0, "say + no person"],
        ["pick", "“I can help.” → She said she ___ help.", ["can", "could", "will"], 1, "can → could"],
        ["pick", "“I’m leaving.” → He said he ___ leaving.", ["is", "was", "were"], 1, "am → was"],
        ["spot", "My friend said me that the exam was easy.", "said me", "told me", "tell + person"],
        ["spot", "She told that she liked the gift.", "told", "said", "say + no person"],
        ["spot", "He said he will send it soon.", "will", "would", "will → would"],
        ["type", "“I don’t know.” → He said he ___ know.", ["didn't", "did not", "didn’t"], "don’t → didn’t"],
        ["order", "She told me that she was moving to Canada.", "told + person + that"],
        ["say", "Report it: Rahul said, “I am hungry.”", ["Rahul said that he was hungry", "Rahul said he was hungry"], "Rahul said (that) he was hungry."],
      ],
      talk: "Report a recent conversation you had with someone: what they said, what they told you, and what you said back.",
    },
    {
      id: "reported-questions",
      title: "She asked me where I lived",
      goal: "Report questions and requests",
      wm: "Direct and Indirect Speech: Questions and Commands",
      intro:
        "Reported questions use statement order and no question mark: She asked me where I lived. Yes/no questions use “if” or “whether”. Requests and orders use ask/tell + person + to + verb: He asked me to wait.",
      rules: [
        ["asked + question word + subject + verb (tense back).", "“Where do you work?” → She asked where I worked.", "“Why are you late?” → He asked why I was late."],
        ["Yes/no questions: asked if / whether.", "“Are you coming?” → He asked if I was coming.", "She asked whether I liked it."],
        ["Requests and orders: ask / tell + person + (not) to + verb.", "“Please sit down.” → He asked me to sit down.", "“Don’t be late.” → She told us not to be late."],
      ],
      mistakes: [
        ["She asked me where do I live.", "She asked me where I lived.", "Statement order, tense back."],
        ["He asked me that am I coming.", "He asked me if I was coming.", "Yes/no: if, and no “that”."],
        ["She told me don’t go.", "She told me not to go.", "tell + person + not to."],
        ["He asked to me to help.", "He asked me to help.", "ask + person, no “to” before the person."],
      ],
      ex: [
        ["pick", "She asked me what ___.", ["is my name", "my name was", "was my name"], 1, "Statement order: my name was."],
        ["pick", "He asked ___ I had eaten.", ["that", "if", "did"], 1, "Yes/no: if."],
        ["pick", "The doctor told me ___ smoking.", ["stop", "to stop", "stopping"], 1, "tell + person + to"],
        ["pick", "My mom told me ___ late.", ["don’t come", "not to come", "to not coming"], 1, "not to + verb"],
        ["spot", "He asked me where was the station.", "was the station", "the station was", "Statement order."],
        ["spot", "She asked me do I like coffee.", "do I like", "if I liked", "Yes/no: if + statement order."],
        ["spot", "The manager told us don't use our phones.", "don't use", "not to use", "tell + not to"],
        ["type", "He asked me ___ open the window. (request)", ["to"], "ask + person + to"],
        ["order", "She asked me why I was so quiet.", "asked + why + statement order"],
        ["say", "Report it: My boss asked, “Can you stay late?”", ["My boss asked if I could stay late", "My boss asked me if I could stay late", "My boss asked whether I could stay late", "My boss asked me whether I could stay late"], "My boss asked (me) if I could stay late."],
      ],
      talk: "Think of a job interview or a meeting you had. Report three questions they asked you and one thing they asked you to do.",
    },
  ],
};
