// The library. `src` is either "se:<Standard Ebooks GitHub repo>" or "pg:<Project Gutenberg id>".
// `osho: true` marks books Osho talks about in "Books I Have Loved"; the rest are more free books by the same authors.

export const CATEGORIES = [
  "Mystics & Scriptures",
  "Philosophy",
  "Poetry",
  "Novels & Plays",
  "Mind & Society",
  "Lives",
];

const M = "Mystics & Scriptures", PH = "Philosophy", PO = "Poetry", N = "Novels & Plays", S = "Mind & Society", L = "Lives";

export const BOOKS = [
  // ── From Osho's list ──────────────────────────────────────────────
  { slug: "thus-spake-zarathustra", src: "se:friedrich-nietzsche_thus-spake-zarathustra_thomas-common", title: "Thus Spake Zarathustra", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", osho: true, blurb: "The first book on Osho’s list. Zarathustra comes down from the mountains to share what he has learned." },
  { slug: "the-brothers-karamazov", src: "se:fyodor-dostoevsky_the-brothers-karamazov_constance-garnett", title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", cat: N, level: "Challenging", osho: true, blurb: "Three brothers and the murder of their father. Dostoevsky’s last and longest novel." },
  { slug: "tao-te-ching", src: "se:laozi_tao-te-ching_james-legge", title: "Tao Te Ching", author: "Lao Tzu", cat: M, level: "Medium", osho: true, blurb: "81 very short chapters about the Tao, or “the Way”." },
  { slug: "gitanjali", src: "se:rabindranath-tagore_gitanjali", title: "Gitanjali", author: "Rabindranath Tagore", cat: PO, level: "Easy", osho: true, blurb: "Short prose poems Tagore wrote as offerings to God. This book won him the Nobel Prize in 1913." },
  { slug: "the-prophet", src: "se:kahlil-gibran_the-prophet", title: "The Prophet", author: "Kahlil Gibran", cat: PO, level: "Easy", osho: true, blurb: "Before he sails home, a wise man answers people’s questions about love, work and life." },
  { slug: "dialogues-of-plato", src: "se:plato_dialogues_benjamin-jowett", startMode: "first", title: "Dialogues", author: "Plato", cat: PH, level: "Challenging", osho: true, blurb: "Conversations in which Socrates asks people what justice, courage and love really are." },
  { slug: "rubaiyat-of-omar-khayyam", src: "se:omar-khayyam_the-rubaiyat-of-omar-khayyam_edward-fitzgerald", title: "The Rubáiyát", author: "Omar Khayyám", cat: PO, level: "Medium", osho: true, blurb: "Short four-line poems about wine, time, and enjoying life while you can." },
  { slug: "leaves-of-grass", src: "se:walt-whitman_leaves-of-grass", title: "Leaves of Grass", author: "Walt Whitman", cat: PO, level: "Medium", osho: true, blurb: "Whitman’s big book of poems about himself, America and ordinary people." },
  { slug: "aesops-fables", src: "se:aesop_fables_v-s-vernon-jones", title: "Fables", author: "Aesop", cat: N, level: "Easy", osho: true, blurb: "Short animal stories, each with a lesson. Good for reading out loud." },
  { slug: "siddhartha", src: "se:hermann-hesse_siddhartha_various-translators", title: "Siddhartha", author: "Hermann Hesse", cat: N, level: "Easy", osho: true, blurb: "A young man in ancient India leaves home to look for enlightenment." },
  { slug: "man-and-superman", src: "se:george-bernard-shaw_man-and-superman", title: "Man and Superman", author: "George Bernard Shaw", cat: N, level: "Medium", osho: true, blurb: "A comedy about love and ideas. It ends with Shaw’s “Maxims for Revolutionists”." },
  { slug: "jesus-the-son-of-man", src: "se:kahlil-gibran_jesus-the-son-of-man", title: "Jesus, the Son of Man", author: "Kahlil Gibran", cat: M, level: "Easy", osho: true, blurb: "People who knew Jesus each describe him in their own words." },
  { slug: "the-madman", src: "se:kahlil-gibran_the-madman", title: "The Madman", author: "Kahlil Gibran", cat: PO, level: "Easy", osho: true, blurb: "Very short parables. Gibran’s first book in English." },
  { slug: "tractatus-logico-philosophicus", src: "se:ludwig-wittgenstein_tractatus-logico-philosophicus_c-k-ogden", title: "Tractatus Logico-Philosophicus", author: "Ludwig Wittgenstein", cat: PH, level: "Challenging", osho: true, blurb: "A short, difficult book of numbered statements about language and logic." },
  { slug: "principia-ethica", src: "se:g-e-moore_principia-ethica", title: "Principia Ethica", author: "G. E. Moore", cat: PH, level: "Challenging", osho: true, blurb: "A philosopher tries to work out what the word “good” actually means." },
  { slug: "analects", src: "se:confucius_analects_james-legge", title: "The Analects", author: "Confucius", cat: PH, level: "Medium", osho: true, blurb: "Short sayings of Confucius, collected by his students." },
  { slug: "alices-adventures-in-wonderland", src: "se:lewis-carroll_alices-adventures-in-wonderland_john-tenniel", title: "Alice’s Adventures in Wonderland", author: "Lewis Carroll", cat: N, level: "Easy", osho: true, blurb: "Alice falls down a rabbit hole into a very strange world." },
  { slug: "through-the-looking-glass", src: "se:lewis-carroll_through-the-looking-glass_john-tenniel", title: "Through the Looking-Glass", author: "Lewis Carroll", cat: N, level: "Easy", osho: true, blurb: "Alice climbs through a mirror into a world set out like a chessboard." },
  { slug: "the-communist-manifesto", src: "se:karl-marx_friedrich-engels_the-communist-manifesto_samuel-moore", title: "The Communist Manifesto", author: "Karl Marx & Friedrich Engels", cat: S, level: "Medium", osho: true, blurb: "The short pamphlet Marx and Engels published in 1848." },
  { slug: "resurrection", src: "se:leo-tolstoy_resurrection_louise-maude", title: "Resurrection", author: "Leo Tolstoy", cat: N, level: "Medium", osho: true, blurb: "A rich man sees a woman he once treated badly on trial, and decides to change his life." },
  { slug: "war-and-peace", src: "se:leo-tolstoy_war-and-peace_louise-maude_aylmer-maude", title: "War and Peace", author: "Leo Tolstoy", cat: N, level: "Challenging", osho: true, blurb: "Russian families during the wars with Napoleon." },
  { slug: "fathers-and-sons", src: "se:ivan-turgenev_fathers-and-children_constance-garnett", title: "Fathers and Sons", author: "Ivan Turgenev", cat: N, level: "Medium", osho: true, blurb: "A young man who rejects every tradition, and the older people around him." },
  { slug: "notes-from-underground", src: "se:fyodor-dostoevsky_notes-from-underground_constance-garnett", title: "Notes from Underground", author: "Fyodor Dostoevsky", cat: N, level: "Challenging", osho: true, blurb: "An angry, lonely man in St. Petersburg talks about himself and the world." },
  { slug: "my-experiments-with-truth", src: "se:mahatma-gandhi_the-story-of-my-experiments-with-truth_mahadev-desai", title: "My Experiments with Truth", author: "Mahatma Gandhi", cat: L, level: "Medium", osho: true, blurb: "Gandhi’s autobiography, from his childhood to the 1920s." },
  { slug: "anna-karenina", src: "se:leo-tolstoy_anna-karenina_constance-garnett", title: "Anna Karenina", author: "Leo Tolstoy", cat: N, level: "Challenging", osho: true, blurb: "A married woman falls in love with another man in 1870s Russia." },

  { slug: "chuang-tzu", src: "pg:59709", title: "Chuang Tzu", author: "Chuang Tzu", cat: M, level: "Challenging", osho: true, blurb: "Funny, strange Taoist stories, including the famous butterfly dream." },
  { slug: "bhagavad-gita", src: "pg:2388", title: "The Bhagavad Gita", subtitle: "The Song Celestial", author: "Translated by Edwin Arnold", cat: M, level: "Medium", osho: true, blurb: "Krishna talks to Arjuna before a great battle. Translated as a long poem." },
  { slug: "the-upanishads", src: "pg:3283", title: "The Upanishads", author: "Translated by Swami Paramananda", cat: M, level: "Medium", osho: true, blurb: "Several Upanishads in English, including the Isa Upanishad." },
  { slug: "golden-verses-of-pythagoras", src: "pg:69174", title: "The Golden Verses of Pythagoras", author: "Pythagoras", cat: PH, level: "Challenging", osho: true, blurb: "Pythagoras’s short rules for living, with a long explanation by the translator." },
  { slug: "yoga-sutras", src: "pg:2526", title: "The Yoga Sutras", author: "Patanjali", cat: M, level: "Medium", osho: true, blurb: "Patanjali’s short sutras on yoga and meditation, with notes." },
  { slug: "songs-of-kabir", src: "pg:6519", title: "Songs of Kabir", author: "Kabir · translated by Tagore", cat: PO, level: "Easy", osho: true, blurb: "Poems by Kabir, the weaver-poet, translated by Tagore." },
  { slug: "the-secret-doctrine", src: "pg:54824", title: "The Secret Doctrine", subtitle: "Volume 1", author: "H. P. Blavatsky", cat: M, level: "Challenging", osho: true, blurb: "The first volume of Blavatsky’s huge book on theosophy." },
  { slug: "the-koran", src: "pg:2800", title: "The Koran", author: "Translated by J. M. Rodwell", cat: M, level: "Challenging", osho: true, blurb: "The holy book of Islam, in J. M. Rodwell’s translation." },
  { slug: "dhammapada", src: "pg:2017", title: "The Dhammapada", author: "The Buddha", cat: M, level: "Easy", osho: true, blurb: "Short sayings of the Buddha, grouped by topic." },
  { slug: "light-on-the-path", src: "pg:14599", title: "Light on the Path", author: "Mabel Collins", cat: M, level: "Medium", osho: true, blurb: "A short book of spiritual advice, first published in 1885." },
  { slug: "the-will-to-power", src: "pg:52914", title: "The Will to Power", subtitle: "Books I and II", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", osho: true, blurb: "Notes from near the end of Nietzsche’s working life, collected after his death." },
  { slug: "introduction-to-psychoanalysis", src: "pg:38219", title: "A General Introduction to Psychoanalysis", author: "Sigmund Freud", cat: S, level: "Medium", osho: true, blurb: "Freud’s lectures introducing psychoanalysis." },
  { slug: "mother", src: "pg:3783", title: "Mother", author: "Maxim Gorky", cat: N, level: "Medium", osho: true, blurb: "A factory worker’s mother slowly joins her son’s revolutionary work." },
  { slug: "psychoanalysis-and-the-unconscious", src: "pg:69219", title: "Psychoanalysis and the Unconscious", author: "D. H. Lawrence", cat: S, level: "Challenging", osho: true, blurb: "D. H. Lawrence’s short reply to Freud." },
  { slug: "the-light-of-asia", src: "pg:8920", title: "The Light of Asia", author: "Edwin Arnold", cat: PO, level: "Medium", osho: true, blurb: "The life of the Buddha, told as a long poem." },
  { slug: "confessions-of-augustine", src: "pg:3296", title: "Confessions", author: "Saint Augustine", cat: M, level: "Challenging", osho: true, blurb: "Augustine writes about his early life and how he came to Christianity." },
  { slug: "poetics", src: "pg:1974", title: "Poetics", author: "Aristotle", cat: PH, level: "Challenging", osho: true, blurb: "Aristotle’s short book about tragedy and how stories are built." },
  { slug: "gita-govinda", src: "pg:25965", title: "The Indian Song of Songs", subtitle: "Gita Govinda and other poems", author: "Jayadeva · translated by Edwin Arnold", cat: PO, level: "Medium", osho: true, blurb: "Poems about Krishna and Radha, with other Indian poems." },
  { slug: "gospel-of-matthew", src: "pg:8040", kjv: true, title: "The Sermon on the Mount", subtitle: "The Gospel of Matthew", author: "King James Bible", cat: M, level: "Medium", osho: true, blurb: "The Gospel of Matthew. The Sermon on the Mount is in chapters 5 to 7." },
  { slug: "song-of-solomon", src: "pg:8022", kjv: true, title: "The Song of Solomon", author: "King James Bible", cat: PO, level: "Medium", osho: true, blurb: "A love poem from the Old Testament, in the King James Bible." },
  { slug: "brahma-sutras", src: "pg:16295", title: "The Brahma Sutras", subtitle: "With Shankara’s commentary", author: "Badarayana", cat: M, level: "Challenging", osho: true, blurb: "The Vedanta Sutras with Shankaracharya’s commentary." },
  { slug: "shri-bhashya", src: "pg:7297", title: "Shri Bhashya", subtitle: "Ramanuja on the Vedanta Sutras", author: "Ramanuja", cat: M, level: "Challenging", osho: true, blurb: "Ramanuja’s commentary on the Vedanta Sutras." },
  { slug: "the-mesnevi", src: "pg:61724", title: "The Masnavi", subtitle: "Book I", author: "Jalaluddin Rumi", cat: PO, level: "Challenging", osho: true, blurb: "The first book of Rumi’s long poem, full of small stories." },
  { slug: "supersensual-life", src: "pg:33742", title: "Dialogues on the Supersensual Life", author: "Jakob Böhme", cat: M, level: "Medium", osho: true, blurb: "A short conversation between a teacher and a student about God." },
  { slug: "mulla-nasruddin", src: "pg:16244", title: "The Turkish Jester", subtitle: "Tales of Nasruddin", author: "Mulla Nasruddin", cat: N, level: "Easy", osho: true, blurb: "Short, funny stories about Nasruddin. Osho told his jokes often." },

  // ── More by these authors ──────────────────────────────────────────
  { slug: "beyond-good-and-evil", src: "se:friedrich-nietzsche_beyond-good-and-evil_helen-zimmern", title: "Beyond Good and Evil", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Nietzsche questions the usual ideas of truth and morality." },
  { slug: "genealogy-of-morals", src: "se:friedrich-nietzsche_the-genealogy-of-morals_horace-b-samuel", title: "The Genealogy of Morals", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Nietzsche asks where our ideas of good, evil and guilt came from." },
  { slug: "the-antichrist", src: "pg:19322", title: "The Antichrist", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Nietzsche’s short, angry attack on Christianity." },
  { slug: "human-all-too-human", src: "pg:38145", title: "Human, All Too Human", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Hundreds of short thoughts, grouped by topic." },
  { slug: "birth-of-tragedy", src: "pg:51356", title: "The Birth of Tragedy", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Nietzsche’s first book, about Greek tragedy." },
  { slug: "dawn-of-day", src: "pg:39955", title: "The Dawn of Day", author: "Friedrich Nietzsche", cat: PH, level: "Challenging", blurb: "Short numbered thoughts on morality." },
  { slug: "crime-and-punishment", src: "se:fyodor-dostoevsky_crime-and-punishment_constance-garnett", title: "Crime and Punishment", author: "Fyodor Dostoevsky", cat: N, level: "Medium", blurb: "A poor student kills a pawnbroker and can’t live with what he has done." },
  { slug: "the-idiot", src: "se:fyodor-dostoevsky_the-idiot_eva-m-martin", title: "The Idiot", author: "Fyodor Dostoevsky", cat: N, level: "Medium", blurb: "A kind, trusting prince returns to Russia and gets pulled into other people’s problems." },
  { slug: "house-of-the-dead", src: "se:fyodor-dostoevsky_the-house-of-the-dead_constance-garnett", title: "The House of the Dead", author: "Fyodor Dostoevsky", cat: N, level: "Medium", blurb: "Life inside a Siberian prison camp, from Dostoevsky’s own experience." },
  { slug: "grand-inquisitor", src: "pg:8578", title: "The Grand Inquisitor", author: "Fyodor Dostoevsky", cat: N, level: "Medium", blurb: "The famous chapter from The Brothers Karamazov, printed on its own." },
  { slug: "a-confession", src: "se:leo-tolstoy_a-confession_aylmer-maude", title: "A Confession", author: "Leo Tolstoy", cat: L, level: "Medium", blurb: "Tolstoy writes about the crisis he went through in his fifties." },
  { slug: "kingdom-of-god-is-within-you", src: "se:leo-tolstoy_the-kingdom-of-god-is-within-you_leo-wiener", title: "The Kingdom of God Is Within You", author: "Leo Tolstoy", cat: S, level: "Challenging", blurb: "Tolstoy’s book on non-violence. Gandhi read it as a young man." },
  { slug: "tolstoy-short-fiction", src: "se:leo-tolstoy_short-fiction_various-translators", title: "Short Fiction", author: "Leo Tolstoy", cat: N, level: "Medium", blurb: "Stories including The Death of Ivan Ilyich and How Much Land Does a Man Need?" },
  { slug: "what-is-art", src: "se:leo-tolstoy_what-is-art_aylmer-maude", title: "What Is Art?", author: "Leo Tolstoy", cat: PH, level: "Medium", blurb: "Tolstoy explains what he thinks art is for." },
  { slug: "steppenwolf", src: "se:hermann-hesse_steppenwolf_basil-creighton", title: "Steppenwolf", author: "Hermann Hesse", cat: N, level: "Medium", blurb: "A lonely middle-aged man who feels half human and half wolf." },
  { slug: "demian", src: "se:hermann-hesse_demian_n-h-priday", title: "Demian", author: "Hermann Hesse", cat: N, level: "Medium", blurb: "A boy growing up and trying to find out who he really is." },
  { slug: "the-forerunner", src: "se:kahlil-gibran_the-forerunner", title: "The Forerunner", author: "Kahlil Gibran", cat: PO, level: "Easy", blurb: "More short parables and poems from Gibran." },
  { slug: "stray-birds", src: "pg:6524", title: "Stray Birds", author: "Rabindranath Tagore", cat: PO, level: "Easy", blurb: "Very short poems, most of them only one or two lines long." },
  { slug: "the-gardener", src: "pg:6686", title: "The Gardener", author: "Rabindranath Tagore", cat: PO, level: "Easy", blurb: "Short love poems by Tagore." },
  { slug: "fruit-gathering", src: "pg:6522", title: "Fruit-Gathering", author: "Rabindranath Tagore", cat: PO, level: "Easy", blurb: "More of Tagore’s devotional poems, similar to Gitanjali." },
  { slug: "the-crescent-moon", src: "pg:6520", title: "The Crescent Moon", author: "Rabindranath Tagore", cat: PO, level: "Easy", blurb: "Poems about children and childhood." },
  { slug: "sadhana", src: "pg:6842", title: "Sadhana", subtitle: "The Realisation of Life", author: "Rabindranath Tagore", cat: M, level: "Medium", blurb: "Lectures Tagore gave in America about spiritual life." },
  { slug: "the-post-office", src: "pg:6523", title: "The Post Office", author: "Rabindranath Tagore", cat: N, level: "Easy", blurb: "A short play about a sick boy who isn’t allowed to leave the house." },
  { slug: "the-hungry-stones", src: "pg:2518", startMode: "first", title: "The Hungry Stones", subtitle: "and Other Stories", author: "Rabindranath Tagore", cat: N, level: "Easy", blurb: "Short stories set in Bengal." },
  { slug: "home-and-the-world", src: "se:rabindranath-tagore_the-home-and-the-world_surendranath-tagore", title: "The Home and the World", author: "Rabindranath Tagore", cat: N, level: "Medium", blurb: "A novel about a marriage in Bengal during the Swadeshi movement." },
  { slug: "my-reminiscences", src: "se:rabindranath-tagore_my-reminiscences_the-macmillan-company", title: "My Reminiscences", author: "Rabindranath Tagore", cat: L, level: "Medium", blurb: "Tagore remembers his childhood and youth." },
  { slug: "gospel-of-buddha", src: "pg:35895", title: "The Gospel of Buddha", author: "Paul Carus", cat: M, level: "Easy", blurb: "The Buddha’s life and teachings, retold in simple language." },
  { slug: "religion-of-the-samurai", src: "pg:5173", title: "The Religion of the Samurai", subtitle: "A Study of Zen", author: "Kaiten Nukariya", cat: M, level: "Medium", blurb: "An early English book on Zen philosophy and practice." },
  { slug: "buddhist-psalms", src: "pg:7015", title: "Buddhist Psalms", author: "Shinran", cat: PO, level: "Easy", blurb: "Poems by the Japanese Buddhist teacher Shinran." },
  { slug: "rumi-persian-mystics", src: "pg:45159", title: "Rumi", subtitle: "The Persian Mystics", author: "Jalaluddin Rumi", cat: PO, level: "Medium", blurb: "Selected poems and stories of Rumi, with an introduction." },
  { slug: "divan-of-hafiz", src: "pg:74883", title: "Poems from the Divan of Hafiz", author: "Hafiz", cat: PO, level: "Medium", blurb: "Poems by Hafiz, translated by Gertrude Bell." },
  { slug: "bustan-of-sadi", src: "pg:60471", title: "The Bustan", author: "Sadi", cat: PO, level: "Medium", blurb: "Stories and advice in verse by the Persian poet Sadi." },
  { slug: "imitation-of-christ", src: "se:thomas-a-kempis_the-imitation-of-christ_william-benham", title: "The Imitation of Christ", author: "Thomas à Kempis", cat: M, level: "Medium", blurb: "A 15th-century Christian book about living a humble life." },
  { slug: "introduction-to-yoga", src: "pg:4278", title: "An Introduction to Yoga", author: "Annie Besant", cat: M, level: "Medium", blurb: "Lectures by Annie Besant explaining yoga." },
  { slug: "autobiography-of-a-yogi", src: "pg:7452", title: "Autobiography of a Yogi", author: "Paramahansa Yogananda", cat: L, level: "Easy", blurb: "Yogananda’s life story, from his childhood in India to his years in America." },
  { slug: "meditations", src: "se:marcus-aurelius_meditations_george-long", title: "Meditations", author: "Marcus Aurelius", cat: PH, level: "Medium", blurb: "Private notes a Roman emperor wrote to himself." },
  { slug: "epictetus", src: "se:epictetus_short-works_george-long", title: "The Enchiridion", subtitle: "and other short works", author: "Epictetus", cat: PH, level: "Medium", blurb: "Short teachings from Epictetus, who was born a slave." },
  { slug: "seneca-dialogues", src: "se:seneca_dialogues_aubrey-stewart", title: "Dialogues", author: "Seneca", cat: PH, level: "Medium", blurb: "Seneca’s essays on anger, calm, and how short life is." },
  { slug: "walden", src: "se:henry-david-thoreau_walden", title: "Walden", author: "Henry David Thoreau", cat: PH, level: "Medium", blurb: "Thoreau writes about the two years he lived in a small cabin by a pond." },
  { slug: "thoreau-essays", src: "se:henry-david-thoreau_essays", title: "Essays", subtitle: "including Civil Disobedience", author: "Henry David Thoreau", cat: S, level: "Medium", blurb: "Thoreau’s essays, including Walking and Civil Disobedience." },
  { slug: "emerson-essays", src: "se:ralph-waldo-emerson_essays", title: "Essays", subtitle: "including Self-Reliance", author: "Ralph Waldo Emerson", cat: PH, level: "Medium", blurb: "Emerson’s best-known essays, including Self-Reliance." },
  { slug: "problems-of-philosophy", src: "se:bertrand-russell_the-problems-of-philosophy", title: "The Problems of Philosophy", author: "Bertrand Russell", cat: PH, level: "Medium", blurb: "A short introduction to philosophy, written for beginners." },
  { slug: "nicomachean-ethics", src: "se:aristotle_nicomachean-ethics_f-h-peters", title: "Nicomachean Ethics", author: "Aristotle", cat: PH, level: "Challenging", blurb: "Aristotle on happiness and how to be a good person." },
  { slug: "the-republic", src: "pg:1497", title: "The Republic", author: "Plato", cat: PH, level: "Challenging", blurb: "Socrates describes an ideal city. The story of the cave comes from this book." },
  { slug: "art-of-war", src: "se:sun-tzu_the-art-of-war_lionel-giles", title: "The Art of War", author: "Sun Tzu", cat: PH, level: "Easy", blurb: "Short lessons on strategy from ancient China." },
  { slug: "divine-comedy", src: "se:dante-alighieri_the-divine-comedy_henry-wadsworth-longfellow", title: "The Divine Comedy", author: "Dante Alighieri", cat: PO, level: "Challenging", blurb: "Dante travels through Hell, Purgatory and Heaven. Translated by Longfellow." },
  { slug: "chekhov-short-fiction", src: "se:anton-chekhov_short-fiction_constance-garnett", title: "Short Fiction", author: "Anton Chekhov", cat: N, level: "Medium", blurb: "Short stories about ordinary Russian people." },
  { slug: "young-werther", src: "se:j-w-von-goethe_the-sorrows-of-young-werther_r-d-boylan", title: "The Sorrows of Young Werther", author: "Johann Wolfgang von Goethe", cat: N, level: "Medium", blurb: "A young man’s letters about a love he cannot have." },
  { slug: "psychology-of-the-unconscious", src: "pg:65903", title: "Psychology of the Unconscious", author: "Carl Jung", cat: S, level: "Challenging", blurb: "Jung’s early book about myths, dreams and the unconscious." },
  { slug: "indian-home-rule", src: "pg:40461", title: "Hind Swaraj", subtitle: "Indian Home Rule", author: "Mahatma Gandhi", cat: S, level: "Medium", blurb: "Gandhi’s short book, written as a conversation, about what freedom for India should mean." },
  { slug: "the-jungle-book", src: "pg:236", title: "The Jungle Book", author: "Rudyard Kipling", cat: N, level: "Easy", blurb: "Mowgli, the boy raised by wolves, and his friends in the Indian jungle." },
];
